<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.32">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<title>3&nbsp; Raster Data Basics with terra – R as GIS for Economists</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>

<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../chapters/04-SpatialInteractionVectorVector.html" rel="next">
<link href="../chapters/02-VectorDataBasics.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-6fa3a3a215baab0a79705e6d9247c621.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script><!-- Google tag (gtag.js) --><script async="" src="https://www.googletagmanager.com/gtag/js?id=G-WEXJ5LCRDJ"></script><script>
  window.dataLayer = window.dataLayer || [];
  function gtag() { dataLayer.push(arguments); }
  gtag('js', new Date());

  gtag('config', 'G-WEXJ5LCRDJ');
</script><script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script><script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script><script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script><link rel="stylesheet" href="../style.css">
</head>
<body class="nav-sidebar floating slimcontent quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav"><div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../chapters/02-VectorDataBasics.html">Foundations</a></li><li class="breadcrumb-item"><a href="../chapters/03-RasterDataBasics.html"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Raster Data Basics with <code>terra</code></span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">R as GIS for Economists</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/tmieno2/R-as-GIS-for-Economists" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
    <div class="dropdown">
      <a href="" title="Share" id="quarto-navigation-tool-dropdown-0" class="quarto-navigation-tool dropdown-toggle px-1" data-bs-toggle="dropdown" aria-expanded="false" role="link" aria-label="Share"><i class="bi bi-share"></i></a>
      <ul class="dropdown-menu" aria-labelledby="quarto-navigation-tool-dropdown-0">
<li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://twitter.com/intent/tweet?url=%7Curl%7C">
              <i class="bi bi-twitter pe-1"></i>
            Twitter
            </a>
          </li>
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://www.facebook.com/sharer/sharer.php?u=%7Curl%7C">
              <i class="bi bi-facebook pe-1"></i>
            Facebook
            </a>
          </li>
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://www.linkedin.com/sharing/share-offsite/?url=%7Curl%7C">
              <i class="bi bi-linkedin pe-1"></i>
            LinkedIn
            </a>
          </li>
      </ul>
</div>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/00-preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="px-0"><hr class="sidebar-divider hi "></li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Demonstrations</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/01-Demonstration.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">R as GIS: Demonstrations</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="px-0"><hr class="sidebar-divider hi "></li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Foundations</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/02-VectorDataBasics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Vector Data Basics with <code>sf</code></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/03-RasterDataBasics.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Raster Data Basics with <code>terra</code></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/04-SpatialInteractionVectorVector.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Spatial Interaction: Vector-Vector</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/05-SpatialInteractionVectorRaster.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Spatial Interaction: Vector-Raster</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="px-0"><hr class="sidebar-divider hi "></li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Extensions</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/07-stars.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Spatiotemporal Raster Data Handling with <code>stars</code></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/08-CreateMaps-ggplot.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Creating Maps using <code>ggplot2</code></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/09-DownloadSpatialData.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Download and process spatial datasets from within R</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="px-0"><hr class="sidebar-divider hi "></li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">(slightly) Advanced Topics</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/10-SpeedThingsUp.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Extraction Speed Considerations</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="px-0"><hr class="sidebar-divider hi "></li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/A1-ParallelComputing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Loop and Parallel Computing</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/A2-ggplot2-appendix.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">ggplot2 minimals</span></span></a>
  </div>
</li>
      </ul>
</li>
    </ul>
</div>
</nav><div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">Table of contents</h2>
   
  <ul>
<li>
<a href="#before-you-start" id="toc-before-you-start" class="nav-link active" data-scroll-target="#before-you-start">Before you start</a>
  <ul class="collapse">
<li><a href="#direction-for-replication" id="toc-direction-for-replication" class="nav-link" data-scroll-target="#direction-for-replication">Direction for replication</a></li>
  </ul>
</li>
  <li>
<a href="#raster-data-object-classes" id="toc-raster-data-object-classes" class="nav-link" data-scroll-target="#raster-data-object-classes"><span class="header-section-number">3.1</span> Raster data object classes</a>
  <ul class="collapse">
<li><a href="#raster-package-rasterlayer-rasterstack-and-rasterbrick" id="toc-raster-package-rasterlayer-rasterstack-and-rasterbrick" class="nav-link" data-scroll-target="#raster-package-rasterlayer-rasterstack-and-rasterbrick"><span class="header-section-number">3.1.1</span> <code>raster</code> package: <code>RasterLayer</code>, <code>RasterStack</code>, and <code>RasterBrick</code></a></li>
  <li><a href="#terra-package-spatraster" id="toc-terra-package-spatraster" class="nav-link" data-scroll-target="#terra-package-spatraster"><span class="header-section-number">3.1.2</span> <code>terra</code> package: <code>SpatRaster</code></a></li>
  <li><a href="#converting-a-spatraster-object-to-a-raster-object." id="toc-converting-a-spatraster-object-to-a-raster-object." class="nav-link" data-scroll-target="#converting-a-spatraster-object-to-a-raster-object."><span class="header-section-number">3.1.3</span> Converting a <code>SpatRaster</code> object to a <code>Raster</code><span class="math inline">\(^*\)</span> object.</a></li>
  <li><a href="#vector-data-in-the-terra-package" id="toc-vector-data-in-the-terra-package" class="nav-link" data-scroll-target="#vector-data-in-the-terra-package"><span class="header-section-number">3.1.4</span> Vector data in the <code>terra</code> package</a></li>
  </ul>
</li>
  <li>
<a href="#read-and-write-a-raster-data-file" id="toc-read-and-write-a-raster-data-file" class="nav-link" data-scroll-target="#read-and-write-a-raster-data-file"><span class="header-section-number">3.2</span> Read and write a raster data file</a>
  <ul class="collapse">
<li><a href="#read-raster-files" id="toc-read-raster-files" class="nav-link" data-scroll-target="#read-raster-files"><span class="header-section-number">3.2.1</span> Read raster file(s)</a></li>
  <li><a href="#write-raster-files" id="toc-write-raster-files" class="nav-link" data-scroll-target="#write-raster-files"><span class="header-section-number">3.2.2</span> Write raster files</a></li>
  </ul>
</li>
  <li>
<a href="#basic-operations" id="toc-basic-operations" class="nav-link" data-scroll-target="#basic-operations"><span class="header-section-number">3.3</span> Basic operations</a>
  <ul class="collapse">
<li><a href="#accessing-the-metadata" id="toc-accessing-the-metadata" class="nav-link" data-scroll-target="#accessing-the-metadata"><span class="header-section-number">3.3.1</span> Accessing the metadata</a></li>
  <li><a href="#get-cell-values" id="toc-get-cell-values" class="nav-link" data-scroll-target="#get-cell-values"><span class="header-section-number">3.3.2</span> Get cell values</a></li>
  <li><a href="#subset-access-particular-layers" id="toc-subset-access-particular-layers" class="nav-link" data-scroll-target="#subset-access-particular-layers"><span class="header-section-number">3.3.3</span> Subset (access particular layers)</a></li>
  <li><a href="#add-a-new-layer" id="toc-add-a-new-layer" class="nav-link" data-scroll-target="#add-a-new-layer"><span class="header-section-number">3.3.4</span> Add a new layer</a></li>
  </ul>
</li>
  <li><a href="#arithmetic-operations" id="toc-arithmetic-operations" class="nav-link" data-scroll-target="#arithmetic-operations"><span class="header-section-number">3.4</span> Arithmetic operations</a></li>
  <li><a href="#turning-a-raster-object-into-a-data.frame-not-necessary" id="toc-turning-a-raster-object-into-a-data.frame-not-necessary" class="nav-link" data-scroll-target="#turning-a-raster-object-into-a-data.frame-not-necessary"><span class="header-section-number">3.5</span> Turning a raster object into a <code>data.frame</code> (not necessary)</a></li>
  <li><a href="#quick-visualization" id="toc-quick-visualization" class="nav-link" data-scroll-target="#quick-visualization"><span class="header-section-number">3.6</span> Quick visualization</a></li>
  <li><a href="#sec-work-with-netcdf" id="toc-sec-work-with-netcdf" class="nav-link" data-scroll-target="#sec-work-with-netcdf"><span class="header-section-number">3.7</span> Working with netCDFs</a></li>
  </ul><div class="toc-actions"><ul><li><a href="https://github.com/tmieno2/R-as-GIS-for-Economists/edit/master/chapters/03-RasterDataBasics.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content page-columns page-full" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../chapters/02-VectorDataBasics.html">Foundations</a></li><li class="breadcrumb-item"><a href="../chapters/03-RasterDataBasics.html"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Raster Data Basics with <code>terra</code></span></a></li></ol></nav><div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title"><span id="sec-raster-basics" class="quarto-section-identifier"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Raster Data Basics with <code>terra</code></span></span></h1><button type="button" class="btn code-tools-button" id="quarto-code-tools-source"><i class="bi"></i> Code</button></div></div>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header><section id="before-you-start" class="level2 unnumbered"><h2 class="unnumbered anchored" data-anchor-id="before-you-start">Before you start</h2>
<p>In this chapter, we will explore how to handle raster data using the <code>raster</code> and <code>terra</code> packages. The <code>raster</code> package has long been the standard for raster data handling, but the <code>terra</code> package has now superseded the <code>raster</code> package. <code>terra</code> typically offers faster performance for many raster operations compared to <code>raster</code>. However, we will still cover <code>raster</code> object classes and how to convert between <code>raster</code> and <code>terra</code> objects. This is because many of the existing spatial packages still rely on <code>raster</code> object classes and have not yet transitioned to <code>terra</code>. Both packages share many function names, and key differences will be clarified as we proceed.</p>
<p>For many scientists, one of the most common and time-consuming raster data task is extracting values for vector data. As such, we will focus on the essential knowledge needed for this process, which will be thoroughly discussed in <a href="05-SpatialInteractionVectorRaster.html" class="quarto-xref"><span>Chapter 5</span></a>.</p>
<p>Finally, if you frequently work with raster data that includes temporal dimensions (e.g., PRISM, Daymet), you may find the <code>stars</code> package useful (covered in <a href="07-stars.html" class="quarto-xref"><span>Chapter 6</span></a>). It offers a data model tailored for time-based raster data and allows the use of <code>dplyr</code> verbs for data manipulation.</p>
<section id="direction-for-replication" class="level3 unnumbered"><h3 class="unnumbered anchored" data-anchor-id="direction-for-replication">Direction for replication</h3>
<p><strong>Datasets</strong></p>
<p>All the datasets that you need to import are available <a href="https://www.dropbox.com/sh/yf1u2gcnjyfbw38/AAD-cYgMyGMIP2kih2Jd6rjGa?dl=0">here</a>. In this chapter, the path to files is set relative to my own working directory (which is hidden). To run the codes without having to mess with paths to the files, follow these steps:</p>
<ul>
<li>set a folder (any folder) as the working directory using <code><a href="https://rdrr.io/r/base/getwd.html">setwd()</a></code><br>
</li>
<li>create a folder called “Data” inside the folder designated as the working directory (if you have created a “Data” folder previously, skip this step)</li>
<li>download the pertinent datasets from <a href="https://www.dropbox.com/sh/yf1u2gcnjyfbw38/AAD-cYgMyGMIP2kih2Jd6rjGa?dl=0">here</a>
</li>
<li>place all the files in the downloaded folder in the “Data” folder</li>
</ul>
<p><strong>Packages</strong></p>
<p>Run the following code to install or load (if already installed) the <code>pacman</code> package, and then install or load (if already installed) the listed package inside the <code><a href="https://rdrr.io/pkg/pacman/man/p_load.html">pacman::p_load()</a></code> function.</p>
<div class="cell">
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw">if</span> <span class="op">(</span><span class="op">!</span><span class="kw"><a href="https://rdrr.io/r/base/library.html">require</a></span><span class="op">(</span><span class="st"><a href="https://github.com/trinker/pacman">"pacman"</a></span><span class="op">)</span><span class="op">)</span> <span class="fu"><a href="https://rdrr.io/r/utils/install.packages.html">install.packages</a></span><span class="op">(</span><span class="st">"pacman"</span><span class="op">)</span></span>
<span><span class="fu">pacman</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/pacman/man/p_load.html">p_load</a></span><span class="op">(</span></span>
<span>  <span class="va">terra</span>, <span class="co"># handle raster data</span></span>
<span>  <span class="va">tidyterra</span>, <span class="co"># handle raster data using dplyr verbs</span></span>
<span>  <span class="va">raster</span>, <span class="co"># handle raster data</span></span>
<span>  <span class="va">mapview</span>, <span class="co"># create interactive maps</span></span>
<span>  <span class="va">dplyr</span>, <span class="co"># data wrangling</span></span>
<span>  <span class="va">sf</span>, <span class="co"># vector data handling</span></span>
<span>  <span class="va">lubridate</span> <span class="co"># date handling</span></span>
<span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section></section><section id="raster-data-object-classes" class="level2 page-columns page-full" data-number="3.1"><h2 data-number="3.1" class="anchored" data-anchor-id="raster-data-object-classes">
<span class="header-section-number">3.1</span> Raster data object classes</h2>
<section id="raster-package-rasterlayer-rasterstack-and-rasterbrick" class="level3 page-columns page-full" data-number="3.1.1"><h3 data-number="3.1.1" class="anchored" data-anchor-id="raster-package-rasterlayer-rasterstack-and-rasterbrick">
<span class="header-section-number">3.1.1</span> <code>raster</code> package: <code>RasterLayer</code>, <code>RasterStack</code>, and <code>RasterBrick</code>
</h3>
<p>Let’s start with taking a look at raster data. We will use the CDL data for Iowa in 2015. We can use <code><a href="https://rdrr.io/pkg/raster/man/raster.html">raster::raster()</a></code> to read a raster data file.</p>
<div class="cell">
<div class="sourceCode" id="cb2"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="op">(</span></span>
<span>  <span class="va">IA_cdl_2015</span> <span class="op">&lt;-</span> <span class="fu">raster</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/raster/man/raster.html">raster</a></span><span class="op">(</span><span class="st">"Data/IA_cdl_2015.tif"</span><span class="op">)</span></span>
<span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>class      : RasterLayer 
dimensions : 11671, 17795, 207685445  (nrow, ncol, ncell)
resolution : 30, 30  (x, y)
extent     : -52095, 481755, 1938165, 2288295  (xmin, xmax, ymin, ymax)
crs        : +proj=aea +lat_0=23 +lon_0=-96 +lat_1=29.5 +lat_2=45.5 +x_0=0 +y_0=0 +datum=NAD83 +units=m +no_defs 
source     : IA_cdl_2015.tif 
names      : Layer_1 
values     : 0, 229  (min, max)</code></pre>
</div>
</div>
<p>Evaluating an imported raster object provides key information about the raster data, such as its dimensions (number of cells, rows, and columns), spatial resolution (e.g., 30 meters by 30 meters for this dataset), extent, coordinate reference system (CRS), and the minimum and maximum values recorded. The downloaded data is of the class <code>RasterLayer</code>, which is defined by the raster package. A <code>RasterLayer</code> contains only one layer, meaning that the raster cells hold the value of a single variable (in this case, the land use category code as an integer)</p>
<hr>
<p>You can stack multiple raster layers of the <strong>same spatial resolution and extent</strong> to create a <code>RasterStack</code> using <code><a href="https://rdrr.io/pkg/raster/man/stack.html">raster::stack()</a></code> or <code>RasterBrick</code> using <code><a href="https://rdrr.io/pkg/raster/man/brick.html">raster::brick()</a></code>. Often times, processing a multi-layer object has computational advantages over processing multiple single-layer one by one<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a>.</p>
<div class="no-row-height column-margin column-container"><div id="fn1"><p><sup>1</sup>&nbsp;You will see this in <a href="05-SpatialInteractionVectorRaster.html" class="quarto-xref"><span>Chapter 5</span></a> where we learn how to extract values from a raster layer for a vector data.</p></div></div><p>To create a RasterStack and RasterBrick, let’s load the CDL data for IA in 2016 and stack it with the 2015 data.</p>
<div class="cell">
<div class="sourceCode" id="cb4"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">IA_cdl_2016</span> <span class="op">&lt;-</span> <span class="fu">raster</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/raster/man/raster.html">raster</a></span><span class="op">(</span><span class="st">"Data/IA_cdl_2016.tif"</span><span class="op">)</span></span>
<span></span>
<span><span class="co">#--- stack the two ---#</span></span>
<span><span class="op">(</span></span>
<span>  <span class="va">IA_cdl_stack</span> <span class="op">&lt;-</span> <span class="fu">raster</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/raster/man/stack.html">stack</a></span><span class="op">(</span><span class="va">IA_cdl_2015</span>, <span class="va">IA_cdl_2016</span><span class="op">)</span></span>
<span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>class      : RasterStack 
dimensions : 11671, 17795, 207685445, 2  (nrow, ncol, ncell, nlayers)
resolution : 30, 30  (x, y)
extent     : -52095, 481755, 1938165, 2288295  (xmin, xmax, ymin, ymax)
crs        : +proj=aea +lat_0=23 +lon_0=-96 +lat_1=29.5 +lat_2=45.5 +x_0=0 +y_0=0 +datum=NAD83 +units=m +no_defs 
names      : Layer_1, IA_cdl_2016 
min values :       0,           0 
max values :     229,         241 </code></pre>
</div>
</div>
<p><code>IA_cdl_stack</code> is of class <code>RasterStack</code>, and it has two layers of variables: CDL for 2015 and 2016. You can make it a <code>RasterBrick</code> using <code><a href="https://rdrr.io/pkg/raster/man/brick.html">raster::brick()</a></code>:</p>
<div class="cell">
<div class="sourceCode" id="cb6"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co">#--- stack the two ---#</span></span>
<span><span class="va">IA_cdl_brick</span> <span class="op">&lt;-</span> <span class="fu">brick</span><span class="op">(</span><span class="va">IA_cdl_stack</span><span class="op">)</span></span>
<span></span>
<span><span class="co">#--- or this works as well ---#</span></span>
<span><span class="co"># IA_cdl_brick &lt;- brick(IA_cdl_2015, IA_cdl_2016)</span></span>
<span></span>
<span><span class="co">#--- take a look ---#</span></span>
<span><span class="va">IA_cdl_brick</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>class      : RasterBrick 
dimensions : 11671, 17795, 207685445, 2  (nrow, ncol, ncell, nlayers)
resolution : 30, 30  (x, y)
extent     : -52095, 481755, 1938165, 2288295  (xmin, xmax, ymin, ymax)
crs        : Error in if (is.na(x)) { : argument is of length zero
 
source     : r_tmp_2023-03-07_111005_60204_86270.grd 
names      : IA_cdl_2015, IA_cdl_2016 
min values :           0,           0 
max values :         229,         241 </code></pre>
</div>
</div>
<p>You probably noticed that it took some time to create the <code>RasterBrick</code> object<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a>. While spatial operations on <code>RasterBrick</code> are supposedly faster than <code>RasterStack</code>, the time to create a <code>RasterBrick</code> object itself is often long enough to kill the speed advantage entirely. Often, the three raster object types are collectively referred to as <code>Raster</code><span class="math inline">\(^*\)</span> objects for shorthand in the documentation of the <code>raster</code> and other related packages.</p>
<div class="no-row-height column-margin column-container"><div id="fn2"><p><sup>2</sup>&nbsp;Read <a href="https://geocompr.robinlovelace.net/spatial-class.html#raster-classes">here</a> for the difference between <code>RasterStack</code> and <code>RasterBrick</code></p></div></div></section><section id="terra-package-spatraster" class="level3" data-number="3.1.2"><h3 data-number="3.1.2" class="anchored" data-anchor-id="terra-package-spatraster">
<span class="header-section-number">3.1.2</span> <code>terra</code> package: <code>SpatRaster</code>
</h3>
<p><code>terra</code> package has only one object class for raster data, <code>SpatRaster</code> and no distinctions between one-layer and multi-layer rasters is necessary. Let’s first convert a <code>RasterLayer</code> to a <code>SpatRaster</code> using <code><a href="https://rspatial.github.io/terra/reference/rast.html">terra::rast()</a></code> function.</p>
<div class="cell">
<div class="sourceCode" id="cb8"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co">#--- convert to a SpatRaster ---#</span></span>
<span><span class="va">IA_cdl_2015_sr</span> <span class="op">&lt;-</span> <span class="fu">terra</span><span class="fu">::</span><span class="fu"><a href="https://rspatial.github.io/terra/reference/rast.html">rast</a></span><span class="op">(</span><span class="va">IA_cdl_2015</span><span class="op">)</span></span>
<span></span>
<span><span class="co">#--- take a look ---#</span></span>
<span><span class="va">IA_cdl_2015_sr</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>class       : SpatRaster 
size        : 11671, 17795, 1  (nrow, ncol, nlyr)
resolution  : 30, 30  (x, y)
extent      : -52095, 481755, 1938165, 2288295  (xmin, xmax, ymin, ymax)
coord. ref. : +proj=aea +lat_0=23 +lon_0=-96 +lat_1=29.5 +lat_2=45.5 +x_0=0 +y_0=0 +datum=NAD83 +units=m +no_defs 
source      : IA_cdl_2015.tif 
color table : 1 
name        : Layer_1 
min value   :       0 
max value   :     229 </code></pre>
</div>
</div>
<p>You can see that the number of layers (<code>nlyr</code> in dimensions) is <span class="math inline">\(1\)</span> because the original object is a <code>RasterLayer</code>, which by definition has only one layer. Now, let’s convert a <code>RasterStack</code> to a <code>SpatRaster</code> using <code><a href="https://rspatial.github.io/terra/reference/rast.html">terra::rast()</a></code>.</p>
<div class="cell">
<div class="sourceCode" id="cb10"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co">#--- convert to a SpatRaster ---#</span></span>
<span><span class="va">IA_cdl_stack_sr</span> <span class="op">&lt;-</span> <span class="fu">terra</span><span class="fu">::</span><span class="fu"><a href="https://rspatial.github.io/terra/reference/rast.html">rast</a></span><span class="op">(</span><span class="va">IA_cdl_stack</span><span class="op">)</span></span>
<span></span>
<span><span class="co">#--- take a look ---#</span></span>
<span><span class="va">IA_cdl_stack_sr</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>class       : SpatRaster 
size        : 11671, 17795, 2  (nrow, ncol, nlyr)
resolution  : 30, 30  (x, y)
extent      : -52095, 481755, 1938165, 2288295  (xmin, xmax, ymin, ymax)
coord. ref. : +proj=aea +lat_0=23 +lon_0=-96 +lat_1=29.5 +lat_2=45.5 +x_0=0 +y_0=0 +datum=NAD83 +units=m +no_defs 
sources     : IA_cdl_2015.tif  
              IA_cdl_2016.tif  
color table : 1, 2 
names       : Layer_1, IA_cdl_2016 
min values  :       0,           0 
max values  :     229,         241 </code></pre>
</div>
</div>
<p>Again, it is a <code>SpatRaster</code>, and you now see that the number of layers is 2. We just confirmed that <code>terra</code> has only one class for raster data whether it is single-layer or multiple-layer ones.</p>
<p>In order to make multi-layer <code>SpatRaster</code> from multiple single-layer <code>SpatRaster</code> you can just use <code><a href="https://rdrr.io/r/base/c.html">c()</a></code> like below:</p>
<div class="cell">
<div class="sourceCode" id="cb12"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co">#--- create a single-layer SpatRaster ---#</span></span>
<span><span class="va">IA_cdl_2016_sr</span> <span class="op">&lt;-</span> <span class="fu">terra</span><span class="fu">::</span><span class="fu"><a href="https://rspatial.github.io/terra/reference/rast.html">rast</a></span><span class="op">(</span><span class="va">IA_cdl_2016</span><span class="op">)</span></span>
<span></span>
<span><span class="co">#--- concatenate ---#</span></span>
<span><span class="op">(</span></span>
<span>  <span class="va">IA_cdl_ml_sr</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="va">IA_cdl_2015_sr</span>, <span class="va">IA_cdl_2016_sr</span><span class="op">)</span></span>
<span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>class       : SpatRaster 
size        : 11671, 17795, 2  (nrow, ncol, nlyr)
resolution  : 30, 30  (x, y)
extent      : -52095, 481755, 1938165, 2288295  (xmin, xmax, ymin, ymax)
coord. ref. : +proj=aea +lat_0=23 +lon_0=-96 +lat_1=29.5 +lat_2=45.5 +x_0=0 +y_0=0 +datum=NAD83 +units=m +no_defs 
sources     : IA_cdl_2015.tif  
              IA_cdl_2016.tif  
color table : 1, 2 
names       : Layer_1, IA_cdl_2016 
min values  :       0,           0 
max values  :     229,         241 </code></pre>
</div>
</div>
</section><section id="converting-a-spatraster-object-to-a-raster-object." class="level3" data-number="3.1.3"><h3 data-number="3.1.3" class="anchored" data-anchor-id="converting-a-spatraster-object-to-a-raster-object.">
<span class="header-section-number">3.1.3</span> Converting a <code>SpatRaster</code> object to a <code>Raster</code><span class="math inline">\(^*\)</span> object.</h3>
<p>You can convert a <code>SpatRaster</code> object to a <code>Raster</code><span class="math inline">\(^*\)</span> object using <code><a href="https://rdrr.io/pkg/raster/man/raster.html">raster::raster()</a></code>, <code><a href="https://rdrr.io/pkg/raster/man/stack.html">raster::stack()</a></code>, and <code><a href="https://rdrr.io/pkg/raster/man/brick.html">raster::brick()</a></code>. Keep in mind that if you use <code>raster::rater()</code> even though <code>SpatRaster</code> has multiple layers, the resulting <code>RasterLayer</code> object has only the first of the multiple layers.</p>
<div class="cell">
<div class="sourceCode" id="cb14"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co">#--- RasterLayer (only 1st layer) ---#</span></span>
<span><span class="va">IA_cdl_stack_sr</span> <span class="op">%&gt;%</span> <span class="fu">raster</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/raster/man/raster.html">raster</a></span><span class="op">(</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>class      : RasterLayer 
dimensions : 11671, 17795, 207685445  (nrow, ncol, ncell)
resolution : 30, 30  (x, y)
extent     : -52095, 481755, 1938165, 2288295  (xmin, xmax, ymin, ymax)
crs        : +proj=aea +lat_0=23 +lon_0=-96 +lat_1=29.5 +lat_2=45.5 +x_0=0 +y_0=0 +datum=NAD83 +units=m +no_defs 
source     : IA_cdl_2015.tif 
names      : Layer_1 
values     : 0, 229  (min, max)</code></pre>
</div>
<div class="sourceCode" id="cb16"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co">#--- RasterLayer ---#</span></span>
<span><span class="va">IA_cdl_stack_sr</span> <span class="op">%&gt;%</span> <span class="fu">raster</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/raster/man/stack.html">stack</a></span><span class="op">(</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>class      : RasterStack 
dimensions : 11671, 17795, 207685445, 2  (nrow, ncol, ncell, nlayers)
resolution : 30, 30  (x, y)
extent     : -52095, 481755, 1938165, 2288295  (xmin, xmax, ymin, ymax)
crs        : +proj=aea +lat_0=23 +lon_0=-96 +lat_1=29.5 +lat_2=45.5 +x_0=0 +y_0=0 +datum=NAD83 +units=m +no_defs 
names      : Layer_1, IA_cdl_2016 
min values :       0,           0 
max values :     229,         241 </code></pre>
</div>
<div class="sourceCode" id="cb18"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co">#--- RasterLayer (this takes some time) ---#</span></span>
<span><span class="va">IA_cdl_stack_sr</span> <span class="op">%&gt;%</span> <span class="fu">raster</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/raster/man/brick.html">brick</a></span><span class="op">(</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>class      : RasterStack 
dimensions : 11671, 17795, 207685445, 2  (nrow, ncol, ncell, nlayers)
resolution : 30, 30  (x, y)
extent     : -52095, 481755, 1938165, 2288295  (xmin, xmax, ymin, ymax)
crs        : +proj=aea +lat_0=23 +lon_0=-96 +lat_1=29.5 +lat_2=45.5 +x_0=0 +y_0=0 +datum=NAD83 +units=m +no_defs 
names      : Layer_1, IA_cdl_2016 
min values :       0,           0 
max values :     229,         241 </code></pre>
</div>
</div>
<p>Instead of these functions, you can simply use <code>as(SpatRast, "Raster")</code> like below:</p>
<div class="cell">
<div class="sourceCode" id="cb20"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">as</span><span class="op">(</span><span class="va">IA_cdl_stack_sr</span>, <span class="st">"Raster"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>class      : RasterStack 
dimensions : 11671, 17795, 207685445, 2  (nrow, ncol, ncell, nlayers)
resolution : 30, 30  (x, y)
extent     : -52095, 481755, 1938165, 2288295  (xmin, xmax, ymin, ymax)
crs        : +proj=aea +lat_0=23 +lon_0=-96 +lat_1=29.5 +lat_2=45.5 +x_0=0 +y_0=0 +datum=NAD83 +units=m +no_defs 
names      : Layer_1, IA_cdl_2016 
min values :       0,           0 
max values :     229,         241 </code></pre>
</div>
</div>
<p>This works for any <code>Raster</code><span class="math inline">\(^*\)</span> object and you do not have to pick the right function like above.</p>
</section><section id="vector-data-in-the-terra-package" class="level3" data-number="3.1.4"><h3 data-number="3.1.4" class="anchored" data-anchor-id="vector-data-in-the-terra-package">
<span class="header-section-number">3.1.4</span> Vector data in the <code>terra</code> package</h3>
<p><code>terra</code> package has its own class for vector data, called <code>SpatVector</code>. While we do not use any of the vector data functionality provided by the <code>terra</code> package, we learn how to convert an <code>sf</code> object to <code>SpatVector</code> because some of the <code>terra</code> functions do not support <code>sf</code> as of now (this will likely be resolved very soon). We will see some use cases of this conversion in <a href="05-SpatialInteractionVectorRaster.html" class="quarto-xref"><span>Chapter 5</span></a> when we learn raster value extractions for vector data using <code><a href="https://rspatial.github.io/terra/reference/extract.html">terra::extract()</a></code>.</p>
<p>As an example, let’s use Illinois county border data.</p>
<div class="cell">
<div class="sourceCode" id="cb22"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co">#--- Illinois county boundary ---#</span></span>
<span><span class="op">(</span></span>
<span>  <span class="va">IL_county</span> <span class="op">&lt;-</span> </span>
<span>    <span class="fu">tigris</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/tigris/man/counties.html">counties</a></span><span class="op">(</span></span>
<span>      state <span class="op">=</span> <span class="st">"Illinois"</span>, </span>
<span>      progress_bar <span class="op">=</span> <span class="cn">FALSE</span></span>
<span>    <span class="op">)</span> <span class="op">%&gt;%</span></span>
<span>    <span class="fu">dplyr</span><span class="fu">::</span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="va">STATEFP</span>, <span class="va">COUNTYFP</span><span class="op">)</span></span>
<span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Simple feature collection with 102 features and 2 fields
Geometry type: MULTIPOLYGON
Dimension:     XY
Bounding box:  xmin: -91.51308 ymin: 36.9703 xmax: -87.01994 ymax: 42.50848
Geodetic CRS:  NAD83
First 10 features:
    STATEFP COUNTYFP                       geometry
86       17      067 MULTIPOLYGON (((-90.90609 4...
92       17      025 MULTIPOLYGON (((-88.69516 3...
131      17      185 MULTIPOLYGON (((-87.89243 3...
148      17      113 MULTIPOLYGON (((-88.91954 4...
158      17      005 MULTIPOLYGON (((-89.37207 3...
159      17      009 MULTIPOLYGON (((-90.53674 3...
213      17      083 MULTIPOLYGON (((-90.1459 39...
254      17      147 MULTIPOLYGON (((-88.46335 4...
266      17      151 MULTIPOLYGON (((-88.48289 3...
303      17      011 MULTIPOLYGON (((-89.16654 4...</code></pre>
</div>
</div>
<p>You can convert an <code>sf</code> object to <code>SpatVector</code> object using <code><a href="https://rspatial.github.io/terra/reference/vect.html">terra::vect()</a></code>.</p>
<div class="cell">
<div class="sourceCode" id="cb24"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="op">(</span></span>
<span>  <span class="va">IL_county_sv</span> <span class="op">&lt;-</span> <span class="fu">terra</span><span class="fu">::</span><span class="fu"><a href="https://rspatial.github.io/terra/reference/vect.html">vect</a></span><span class="op">(</span><span class="va">IL_county</span><span class="op">)</span></span>
<span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> class       : SpatVector 
 geometry    : polygons 
 dimensions  : 102, 2  (geometries, attributes)
 extent      : -91.51308, -87.01994, 36.9703, 42.50848  (xmin, xmax, ymin, ymax)
 coord. ref. : lon/lat NAD83 (EPSG:4269) 
 names       : STATEFP COUNTYFP
 type        :   &lt;chr&gt;    &lt;chr&gt;
 values      :      17      067
                    17      025
                    17      185</code></pre>
</div>
</div>
</section></section><section id="read-and-write-a-raster-data-file" class="level2 page-columns page-full" data-number="3.2"><h2 data-number="3.2" class="anchored" data-anchor-id="read-and-write-a-raster-data-file">
<span class="header-section-number">3.2</span> Read and write a raster data file</h2>
<p>Raster data files can come in numerous different formats. For example, PRPISM comes in the Band Interleaved by Line (BIL) format, some of the Daymet data comes in netCDF format. Other popular formats include GeoTiff, SAGA, ENVI, and many others.</p>
<section id="read-raster-files" class="level3" data-number="3.2.1"><h3 data-number="3.2.1" class="anchored" data-anchor-id="read-raster-files">
<span class="header-section-number">3.2.1</span> Read raster file(s)</h3>
<p>You can use <code><a href="https://rspatial.github.io/terra/reference/rast.html">terra::rast()</a></code> to read raster data in many common formats, and in most cases, this function will work for your raster data. In this example, we read a GeoTIFF file (with a .tif extension).</p>
<div class="cell">
<div class="sourceCode" id="cb26"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="op">(</span></span>
<span>  <span class="va">IA_cdl_2015_sr</span> <span class="op">&lt;-</span> <span class="fu">terra</span><span class="fu">::</span><span class="fu"><a href="https://rspatial.github.io/terra/reference/rast.html">rast</a></span><span class="op">(</span><span class="st">"Data/IA_cdl_2015.tif"</span><span class="op">)</span></span>
<span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>class       : SpatRaster 
size        : 11671, 17795, 1  (nrow, ncol, nlyr)
resolution  : 30, 30  (x, y)
extent      : -52095, 481755, 1938165, 2288295  (xmin, xmax, ymin, ymax)
coord. ref. : +proj=aea +lat_0=23 +lon_0=-96 +lat_1=29.5 +lat_2=45.5 +x_0=0 +y_0=0 +datum=NAD83 +units=m +no_defs 
source      : IA_cdl_2015.tif 
color table : 1 
name        : Layer_1 
min value   :       0 
max value   :     229 </code></pre>
</div>
</div>
<p>You can read multiple single-layer raster datasets of the same spatial extent and resolution at the same time to have a multi-layer <code>SpatRaster</code> object. Here, we import two single-layer raster datasets (IA_cdl_2015.tif and IA_cdl_2016.tif) to create a two-layer <code>SpatRaster</code> object.</p>
<div class="cell">
<div class="sourceCode" id="cb28"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co">#--- the list of path to the files ---#</span></span>
<span><span class="va">files_list</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Data/IA_cdl_2015.tif"</span>, <span class="st">"Data/IA_cdl_2016.tif"</span><span class="op">)</span></span>
<span></span>
<span><span class="co">#--- read the two at the same time ---#</span></span>
<span><span class="op">(</span></span>
<span>  <span class="va">multi_layer_sr</span> <span class="op">&lt;-</span> <span class="fu">terra</span><span class="fu">::</span><span class="fu"><a href="https://rspatial.github.io/terra/reference/rast.html">rast</a></span><span class="op">(</span><span class="va">files_list</span><span class="op">)</span></span>
<span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>class       : SpatRaster 
size        : 11671, 17795, 2  (nrow, ncol, nlyr)
resolution  : 30, 30  (x, y)
extent      : -52095, 481755, 1938165, 2288295  (xmin, xmax, ymin, ymax)
coord. ref. : +proj=aea +lat_0=23 +lon_0=-96 +lat_1=29.5 +lat_2=45.5 +x_0=0 +y_0=0 +datum=NAD83 +units=m +no_defs 
sources     : IA_cdl_2015.tif  
              IA_cdl_2016.tif  
color table : 1, 2 
names       : Layer_1, IA_cdl_2016 
min values  :       0,           0 
max values  :     229,         241 </code></pre>
</div>
</div>
<p>Of course, this only works because the two datasets have the identical spatial extent and resolution. There are, however, no restrictions on what variable each of the raster layers represent. For example, you can combine PRISM temperature and precipitation raster layers if you want.</p>
</section><section id="write-raster-files" class="level3 page-columns page-full" data-number="3.2.2"><h3 data-number="3.2.2" class="anchored" data-anchor-id="write-raster-files">
<span class="header-section-number">3.2.2</span> Write raster files</h3>
<p>You can write a <code>SpatRaster</code> object using <code><a href="https://rspatial.github.io/terra/reference/writeRaster.html">terra::writeRaster()</a></code>.</p>
<div class="cell">
<div class="sourceCode" id="cb30"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">terra</span><span class="fu">::</span><span class="fu"><a href="https://rspatial.github.io/terra/reference/writeRaster.html">writeRaster</a></span><span class="op">(</span><span class="va">IA_cdl_2015_sr</span>, <span class="st">"Data/IA_cdl_stack.tif"</span>, filetype <span class="op">=</span> <span class="st">"GTiff"</span>, overwrite <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The above code saves <code>IA_cdl_2015_sr</code> (a <code>SpatRaster</code> object) as a GeoTiff file.<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a> The filetype option can be dropped as <code>writeRaster()</code> infers the filetype from the extension of the file name. The <code>overwrite = TRUE</code> option is necessary if a file with the same name already exists and you are overwriting it. This is one of the many areas <code>terra</code> is better than <code>raster</code>. <code><a href="https://rspatial.github.io/terra/reference/writeRaster.html">raster::writeRaster()</a></code> can be frustratingly slow for a large <code>Raster</code><span class="math inline">\(^*\)</span> object. <code><a href="https://rspatial.github.io/terra/reference/writeRaster.html">terra::writeRaster()</a></code> is much faster.</p>
<div class="no-row-height column-margin column-container"><div id="fn3"><p><sup>3</sup>&nbsp;There are many other alternative formats (see <a href="https://www.rdocumentation.org/packages/raster/versions/3.0-12/topics/writeRaster">here</a>)</p></div></div><p>You can also save a multi-layer <code>SpatRaster</code> object just like you save a single-layer <code>SpatRaster</code> object.</p>
<div class="cell">
<div class="sourceCode" id="cb31"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">terra</span><span class="fu">::</span><span class="fu"><a href="https://rspatial.github.io/terra/reference/writeRaster.html">writeRaster</a></span><span class="op">(</span><span class="va">IA_cdl_stack_sr</span>, <span class="st">"Data/IA_cdl_stack.tif"</span>, filetype <span class="op">=</span> <span class="st">"GTiff"</span>, overwrite <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The saved file is a multi-band raster datasets. So, if you have many raster files of the same spatial extent and resolution, you can “stack” them on R and then export it to a single multi-band raster datasets, which cleans up your data folder.</p>
</section></section><section id="basic-operations" class="level2" data-number="3.3"><h2 data-number="3.3" class="anchored" data-anchor-id="basic-operations">
<span class="header-section-number">3.3</span> Basic operations</h2>
<section id="accessing-the-metadata" class="level3" data-number="3.3.1"><h3 data-number="3.3.1" class="anchored" data-anchor-id="accessing-the-metadata">
<span class="header-section-number">3.3.1</span> Accessing the metadata</h3>
<section id="extent-and-dimensions" class="level4" data-number="3.3.1.1"><h4 data-number="3.3.1.1" class="anchored" data-anchor-id="extent-and-dimensions">
<span class="header-section-number">3.3.1.1</span> Extent and dimensions</h4>
<p>The spatial extent of a <code>SpatRaster</code> object is like a bouding box for an <code>sf</code> object. It can be used to crop a <code>SpatRaster</code> or <code>sf</code> object.</p>
<div class="cell">
<div class="sourceCode" id="cb32"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">terra</span><span class="fu">::</span><span class="fu"><a href="https://rspatial.github.io/terra/reference/ext.html">ext</a></span><span class="op">(</span><span class="va">IA_cdl_ml_sr</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>SpatExtent : -52095, 481755, 1938165, 2288295 (xmin, xmax, ymin, ymax)</code></pre>
</div>
</div>
<p>You can access the dimensions of a <code>SpatRaster</code> object as follows:</p>
<div class="cell">
<div class="sourceCode" id="cb34"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co">#--- number of columns ---#</span></span>
<span><span class="fu">terra</span><span class="fu">::</span><span class="fu"><a href="https://rspatial.github.io/terra/reference/dimensions.html">ncol</a></span><span class="op">(</span><span class="va">IA_cdl_ml_sr</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 17795</code></pre>
</div>
<div class="sourceCode" id="cb36"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co">#--- number of rows ---#</span></span>
<span><span class="fu">terra</span><span class="fu">::</span><span class="fu"><a href="https://rspatial.github.io/terra/reference/dimensions.html">nrow</a></span><span class="op">(</span><span class="va">IA_cdl_ml_sr</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 11671</code></pre>
</div>
<div class="sourceCode" id="cb38"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co">#--- number of layers ---#</span></span>
<span><span class="fu">terra</span><span class="fu">::</span><span class="fu"><a href="https://rspatial.github.io/terra/reference/dimensions.html">nlyr</a></span><span class="op">(</span><span class="va">IA_cdl_ml_sr</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2</code></pre>
</div>
<div class="sourceCode" id="cb40"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co">#--- number of cells ---#</span></span>
<span><span class="fu">terra</span><span class="fu">::</span><span class="fu"><a href="https://rspatial.github.io/terra/reference/dimensions.html">ncell</a></span><span class="op">(</span><span class="va">IA_cdl_ml_sr</span><span class="op">)</span> </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 207685445</code></pre>
</div>
</div>
</section><section id="get-crs" class="level4" data-number="3.3.1.2"><h4 data-number="3.3.1.2" class="anchored" data-anchor-id="get-crs">
<span class="header-section-number">3.3.1.2</span> Get CRS</h4>
<p>You often need to extract the CRS of a raster object before you interact it with vector data (e.g., extracting values from a raster layer to vector data, or cropping a raster layer to the spatial extent of vector data), which can be done using <code><a href="https://rspatial.github.io/terra/reference/crs.html">terra::crs()</a></code>:</p>
<div class="cell">
<div class="sourceCode" id="cb42"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">terra</span><span class="fu">::</span><span class="fu"><a href="https://rspatial.github.io/terra/reference/crs.html">crs</a></span><span class="op">(</span><span class="va">IA_cdl_ml_sr</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "PROJCRS[\"unknown\",\n    BASEGEOGCRS[\"NAD83\",\n        DATUM[\"North American Datum 1983\",\n            ELLIPSOID[\"GRS 1980\",6378137,298.257222101004,\n                LENGTHUNIT[\"metre\",1]]],\n        PRIMEM[\"Greenwich\",0,\n            ANGLEUNIT[\"degree\",0.0174532925199433]],\n        ID[\"EPSG\",4269]],\n    CONVERSION[\"Albers Equal Area\",\n        METHOD[\"Albers Equal Area\",\n            ID[\"EPSG\",9822]],\n        PARAMETER[\"Latitude of false origin\",23,\n            ANGLEUNIT[\"degree\",0.0174532925199433],\n            ID[\"EPSG\",8821]],\n        PARAMETER[\"Longitude of false origin\",-96,\n            ANGLEUNIT[\"degree\",0.0174532925199433],\n            ID[\"EPSG\",8822]],\n        PARAMETER[\"Latitude of 1st standard parallel\",29.5,\n            ANGLEUNIT[\"degree\",0.0174532925199433],\n            ID[\"EPSG\",8823]],\n        PARAMETER[\"Latitude of 2nd standard parallel\",45.5,\n            ANGLEUNIT[\"degree\",0.0174532925199433],\n            ID[\"EPSG\",8824]],\n        PARAMETER[\"Easting at false origin\",0,\n            LENGTHUNIT[\"metre\",1],\n            ID[\"EPSG\",8826]],\n        PARAMETER[\"Northing at false origin\",0,\n            LENGTHUNIT[\"metre\",1],\n            ID[\"EPSG\",8827]]],\n    CS[Cartesian,2],\n        AXIS[\"easting\",east,\n            ORDER[1],\n            LENGTHUNIT[\"metre\",1,\n                ID[\"EPSG\",9001]]],\n        AXIS[\"northing\",north,\n            ORDER[2],\n            LENGTHUNIT[\"metre\",1,\n                ID[\"EPSG\",9001]]]]"</code></pre>
</div>
</div>
</section></section><section id="get-cell-values" class="level3" data-number="3.3.2"><h3 data-number="3.3.2" class="anchored" data-anchor-id="get-cell-values">
<span class="header-section-number">3.3.2</span> Get cell values</h3>
<p>You can access the values stored in a <code>SpatRaster</code> object using the <code><a href="https://rspatial.github.io/terra/reference/values.html">terra::values()</a></code> function or <code>[]</code>:</p>
<p><strong><code><a href="https://rspatial.github.io/terra/reference/values.html">terra::values()</a></code></strong></p>
<div class="cell">
<div class="sourceCode" id="cb44"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co">#--- terra::values ---#</span></span>
<span><span class="va">values_from_ml_sr</span> <span class="op">&lt;-</span> <span class="fu">terra</span><span class="fu">::</span><span class="fu"><a href="https://rspatial.github.io/terra/reference/values.html">values</a></span><span class="op">(</span><span class="va">IA_cdl_ml_sr</span><span class="op">)</span></span>
<span></span>
<span><span class="co">#--- take a look ---#</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">values_from_ml_sr</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>     Layer_1 IA_cdl_2016
[1,]       0           0
[2,]       0           0
[3,]       0           0
[4,]       0           0
[5,]       0           0
[6,]       0           0</code></pre>
</div>
</div>
<p><strong><code>[]</code></strong></p>
<div class="cell">
<div class="sourceCode" id="cb46"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co">#--- terra::values ---#</span></span>
<span><span class="va">values_from_ml_sr</span> <span class="op">&lt;-</span> <span class="va">IA_cdl_ml_sr</span><span class="op">[</span><span class="op">]</span></span>
<span></span>
<span><span class="co">#--- take a look ---#</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">values_from_ml_sr</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>     Layer_1 IA_cdl_2016
[1,]       0           0
[2,]       0           0
[3,]       0           0
[4,]       0           0
[5,]       0           0
[6,]       0           0</code></pre>
</div>
</div>
<p>The returned values come in a matrix form of two columns because we are getting values from a two-layer <code>SpatRaster</code> object (one column for each layer). In general, <code><a href="https://rspatial.github.io/terra/reference/values.html">terra::values()</a></code> returns a <span class="math inline">\(X\)</span> by <span class="math inline">\(n\)</span> matrix, where <span class="math inline">\(X\)</span> is the number of cells and <span class="math inline">\(n\)</span> is the number of layers.</p>
</section><section id="subset-access-particular-layers" class="level3" data-number="3.3.3"><h3 data-number="3.3.3" class="anchored" data-anchor-id="subset-access-particular-layers">
<span class="header-section-number">3.3.3</span> Subset (access particular layers)</h3>
<p>You can access specific layers in a multi-layer raster object by using the <code><a href="https://rdrr.io/r/base/subset.html">subset()</a></code> function with either the name of the layers or their numerical indices specified.</p>
<div class="cell">
<div class="sourceCode" id="cb48"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/subset.html">subset</a></span><span class="op">(</span><span class="va">IA_cdl_ml_sr</span>, <span class="st">"IA_cdl_2016"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>class       : SpatRaster 
size        : 11671, 17795, 1  (nrow, ncol, nlyr)
resolution  : 30, 30  (x, y)
extent      : -52095, 481755, 1938165, 2288295  (xmin, xmax, ymin, ymax)
coord. ref. : +proj=aea +lat_0=23 +lon_0=-96 +lat_1=29.5 +lat_2=45.5 +x_0=0 +y_0=0 +datum=NAD83 +units=m +no_defs 
source      : IA_cdl_2016.tif 
color table : 1 
name        : IA_cdl_2016 
min value   :           0 
max value   :         241 </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode" id="cb50"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co">#--- second layer ---#</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/subset.html">subset</a></span><span class="op">(</span><span class="va">IA_cdl_ml_sr</span>, <span class="fl">2</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>class       : SpatRaster 
size        : 11671, 17795, 1  (nrow, ncol, nlyr)
resolution  : 30, 30  (x, y)
extent      : -52095, 481755, 1938165, 2288295  (xmin, xmax, ymin, ymax)
coord. ref. : +proj=aea +lat_0=23 +lon_0=-96 +lat_1=29.5 +lat_2=45.5 +x_0=0 +y_0=0 +datum=NAD83 +units=m +no_defs 
source      : IA_cdl_2016.tif 
color table : 1 
name        : IA_cdl_2016 
min value   :           0 
max value   :         241 </code></pre>
</div>
</div>
<p>If you are accessing a single layer, you can use a familiar-looking syntax using <code>$</code> like below:</p>
<div class="cell">
<div class="sourceCode" id="cb52"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">IA_cdl_ml_sr</span><span class="op">$</span><span class="va">IA_cdl_2016</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>class       : SpatRaster 
size        : 11671, 17795, 1  (nrow, ncol, nlyr)
resolution  : 30, 30  (x, y)
extent      : -52095, 481755, 1938165, 2288295  (xmin, xmax, ymin, ymax)
coord. ref. : +proj=aea +lat_0=23 +lon_0=-96 +lat_1=29.5 +lat_2=45.5 +x_0=0 +y_0=0 +datum=NAD83 +units=m +no_defs 
source      : IA_cdl_2016.tif 
color table : 1 
name        : IA_cdl_2016 
min value   :           0 
max value   :         241 </code></pre>
</div>
</div>
</section><section id="add-a-new-layer" class="level3" data-number="3.3.4"><h3 data-number="3.3.4" class="anchored" data-anchor-id="add-a-new-layer">
<span class="header-section-number">3.3.4</span> Add a new layer</h3>
<p>You can create a new layer to a <code>SpatRaster</code> object in a very similar syntax as creating a new variable to a <code>data.frame</code> like below:</p>
<div class="cell">
<div class="sourceCode" id="cb54"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co">#--- create a new layer called new_layer ---#</span></span>
<span><span class="op">(</span></span>
<span><span class="va">IA_cdl_ml_sr</span><span class="op">$</span><span class="va">new_layer</span> <span class="op">&lt;-</span> <span class="va">IA_cdl_ml_sr</span><span class="op">$</span><span class="va">IA_cdl_2016</span></span>
<span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>class       : SpatRaster 
size        : 11671, 17795, 1  (nrow, ncol, nlyr)
resolution  : 30, 30  (x, y)
extent      : -52095, 481755, 1938165, 2288295  (xmin, xmax, ymin, ymax)
coord. ref. : +proj=aea +lat_0=23 +lon_0=-96 +lat_1=29.5 +lat_2=45.5 +x_0=0 +y_0=0 +datum=NAD83 +units=m +no_defs 
source      : IA_cdl_2016.tif 
color table : 1 
name        : IA_cdl_2016 
min value   :           0 
max value   :         241 </code></pre>
</div>
</div>
<p>Here, we created a new layer called <code>new_layer</code> to <code>IA_cdl_ml_sr</code>, where the values stored in the new layer are simply the valuesn stored in the <code>IA_cdl_2016</code> layer.</p>
</section></section><section id="arithmetic-operations" class="level2 page-columns page-full" data-number="3.4"><h2 data-number="3.4" class="anchored" data-anchor-id="arithmetic-operations">
<span class="header-section-number">3.4</span> Arithmetic operations</h2>
<p>You can do basic arithmetic operations (addition, subtraction, division, etc) using raster layers as long as they share the same spatial extent and resolution.</p>
<p>Raster arithmetic operations are done <strong>element-by-element</strong> (cell-by-cell) just like vector arithmetic operations. That is, when two layers are added, then the two values associated with the same cell are added and the resulting value becomes the new value for the cell in the newly created RasterLayer.</p>
<p>As a demonstration, let’s try to calculate NDVI from NIR and RED. The mathematical definition of NDVI is as follows:</p>
<span class="math display">\[\begin{align}
NDVI = (NIR-RED)/(NIR+RED)
\end{align}\]</span>
<p>Let’s first import NIR and RED.</p>
<div class="cell">
<div class="sourceCode" id="cb56"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">NIR_and_RED</span> <span class="op">&lt;-</span> <span class="fu">terra</span><span class="fu">::</span><span class="fu"><a href="https://rspatial.github.io/terra/reference/rast.html">rast</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Data/NIR.tif"</span>, <span class="st">"Data/RED.tif"</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Let’s use the formula to calculate NDVI:</p>
<div class="cell">
<div class="sourceCode" id="cb57"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">NIR_and_RED</span><span class="op">$</span><span class="va">NDVI</span> <span class="op">&lt;-</span> <span class="op">(</span><span class="va">NIR_and_RED</span><span class="op">$</span><span class="va">NIR</span> <span class="op">-</span> <span class="va">NIR_and_RED</span><span class="op">$</span><span class="va">RED</span><span class="op">)</span><span class="op">/</span><span class="op">(</span><span class="va">NIR_and_RED</span><span class="op">$</span><span class="va">NIR</span> <span class="op">+</span> <span class="va">NIR_and_RED</span><span class="op">$</span><span class="va">RED</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now, we have a layer named <code>NDVI</code> in <code>NIR_and_RED</code>.</p>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>The <code>tidyterra</code> package can help you make the codes a bit easier to read by allowing the user to use <code>dplyr</code> verbs. For example, the above code can be written as below in place:</p>
<div class="cell">
<div class="sourceCode" id="cb58"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">dplyr</span><span class="fu">::</span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span><span class="va">NIR_and_RED</span>, NDVI <span class="op">=</span> <span class="op">(</span><span class="va">NIR</span> <span class="op">-</span> <span class="va">RED</span><span class="op">)</span><span class="op">/</span><span class="op">(</span><span class="va">NIR</span> <span class="op">+</span> <span class="va">RED</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>class       : SpatRaster 
size        : 482, 239, 3  (nrow, ncol, nlyr)
resolution  : 1.7588, 1.7588  (x, y)
extent      : 286164.7, 286585.1, 4433250, 4434097  (xmin, xmax, ymin, ymax)
coord. ref. : WGS 84 / UTM zone 15N (EPSG:32615) 
source(s)   : memory
names       :       NIR,         RED,       NDVI 
min values  : 0.1337836, 0.008001335, 0.04743315 
max values  : 0.6723093, 0.377668530, 0.94821922 </code></pre>
</div>
</div>
<p>There are other <code>dplyr</code> verbs (not all) you can use to <code>SpatRaster</code>. See <a href="">here</a> for more detailed explanations of how <code>tidyterra</code> works. We will use the package also to visualize <code>SpatRaster</code> objected later in <a href="08-CreateMaps-ggplot.html" class="quarto-xref"><span>Chapter 7</span></a>.</p>
</div>
</div>
<p>You can also apply mathematical functions to the layers like below<a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a>:</p>
<div class="no-row-height column-margin column-container"><div id="fn4"><p><sup>4</sup>&nbsp;The calculated numers are not meaningful. This is just a demonstration of using mathematical functions.</p></div></div><div class="cell">
<div class="sourceCode" id="cb60"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/Log.html">log</a></span><span class="op">(</span><span class="va">NIR_and_RED</span><span class="op">$</span><span class="va">NIR</span><span class="op">)</span> <span class="op">+</span> <span class="va">NIR_and_RED</span><span class="op">$</span><span class="va">RED</span><span class="op">^</span><span class="fl">2</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>class       : SpatRaster 
size        : 482, 239, 1  (nrow, ncol, nlyr)
resolution  : 1.7588, 1.7588  (x, y)
extent      : 286164.7, 286585.1, 4433250, 4434097  (xmin, xmax, ymin, ymax)
coord. ref. : WGS 84 / UTM zone 15N (EPSG:32615) 
source(s)   : memory
varname     : NIR 
name        :       NIR 
min value   : -2.011367 
max value   : -0.394775 </code></pre>
</div>
</div>
</section><section id="turning-a-raster-object-into-a-data.frame-not-necessary" class="level2 page-columns page-full" data-number="3.5"><h2 data-number="3.5" class="anchored" data-anchor-id="turning-a-raster-object-into-a-data.frame-not-necessary">
<span class="header-section-number">3.5</span> Turning a raster object into a <code>data.frame</code> (not necessary)</h2>
<p>You can use the <code><a href="https://rdrr.io/r/base/as.data.frame.html">as.data.frame()</a></code> function with <code>xy = TRUE</code> option to construct a <code>data.frame</code> where each row represents a single cell that has cell values for each layer and its coordinates (the center of the cell).</p>
<div class="cell">
<div class="sourceCode" id="cb62"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co">#--- converting to a data.frame ---#</span></span>
<span><span class="va">IA_cdl_df</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/as.data.frame.html">as.data.frame</a></span><span class="op">(</span><span class="va">IA_cdl_stack_sr</span>, xy <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span> <span class="co"># this works with Raster* objects as well</span></span>
<span></span>
<span><span class="co">#--- take a look ---#</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">IA_cdl_df</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>       x       y Layer_1 Layer_1.1
1 -52080 2288280       0         0
2 -52050 2288280       0         0
3 -52020 2288280       0         0
4 -51990 2288280       0         0
5 -51960 2288280       0         0
6 -51930 2288280       0         0</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-important no-icon callout-titled" title="Caveat">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Caveat
</div>
</div>
<div class="callout-body-container callout-body">
<p>I have seen cases where <code>raster</code> objects are converted to a <code>data.frame</code> and then to an <code>sf</code> object for interacting with polygons using <code><a href="https://r-spatial.github.io/sf/reference/st_join.html">sf::st_join()</a></code> to extract and assign cell values to polygons (see <a href="04-SpatialInteractionVectorVector.html" class="quarto-xref"><span>Chapter 4</span></a> for this type of operation). However, this approach is generally not recommended for two main reasons.</p>
<p>First, it is significantly slower than using functions designed to work directly with raster objects and polygons, such as <code><a href="https://rspatial.github.io/terra/reference/extract.html">terra::extract()</a></code> or <code><a href="https://isciences.gitlab.io/exactextractr/reference/exact_extract.html">exactextractr::exact_extract()</a></code>, which are introduced in <a href="05-SpatialInteractionVectorRaster.html" class="quarto-xref"><span>Chapter 5</span></a>. The primary reason is that converting a raster to a data.frame is a time-consuming process.</p>
<p>Second, once a raster object is converted to point <code>sf</code> data, it becomes impossible to weight cell values based on their degree of overlap with the target polygons. While working with a <code>data.frame</code> may be appealing due to their familiarity, the conversion is often unnecessary and inefficient<a href="#fn5" class="footnote-ref" id="fnref5" role="doc-noteref"><sup>5</sup></a>.</p>
</div>
</div>
<div class="no-row-height column-margin column-container"><div id="fn5"><p><sup>5</sup>&nbsp;If you know of cases where converting to a <code>data.frame</code> is beneficial or necessary, please let me know, and I will include them here.</p></div></div></section><section id="quick-visualization" class="level2" data-number="3.6"><h2 data-number="3.6" class="anchored" data-anchor-id="quick-visualization">
<span class="header-section-number">3.6</span> Quick visualization</h2>
<p>To have a quick visualization of the data values of <code>SpatRaster</code> objects, you can simply use <code><a href="https://rdrr.io/r/graphics/plot.default.html">plot()</a></code>:</p>
<div class="cell">
<div class="sourceCode" id="cb64"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">IA_cdl_2015_sr</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="03-RasterDataBasics_files/figure-html/plot_stack-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>For a more elaborate map using raster data, see <a href="08-CreateMaps-ggplot.html#sec-geom-raster" class="quarto-xref"><span>Section 7.2</span></a>.</p>
</section><section id="sec-work-with-netcdf" class="level2 page-columns page-full" data-number="3.7"><h2 data-number="3.7" class="anchored" data-anchor-id="sec-work-with-netcdf">
<span class="header-section-number">3.7</span> Working with netCDFs</h2>
<p>A netCDF file contains data with a specific structure: a two-dimensional spatial grid (e.g., longitude and latitude) and a third dimension which is usually date or time. This structure is convenient for weather data measured on a consistent grid over time. One such dataset is called <a href="http://www.climatologylab.org/gridmet.html">gridMET</a> which maintains a gridded dataset of weather variables at 4km resolution. Let’s download the daily precipitation data for 2018 using <code><a href="https://rdrr.io/pkg/downloader/man/download.html">downloader::download()</a></code><a href="#fn6" class="footnote-ref" id="fnref6" role="doc-noteref"><sup>6</sup></a>. We set the destination file name (what to call the file and where we want it to be), and the mode to <code>wb</code> for a binary download.</p>
<div class="no-row-height column-margin column-container"><div id="fn6"><p><sup>6</sup>&nbsp;gridMET data is also available in the <a href="https://developers.google.com/earth-engine/datasets/">Google Earth Engine Data Catalog</a>, which can be accessed with the R library <a href="https://github.com/r-spatial/rgee"><code>rgee</code></a></p></div></div><div class="cell">
<div class="sourceCode" id="cb65"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co">#--- download gridMET precipitation 2018 ---#</span></span>
<span><span class="fu">downloader</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/downloader/man/download.html">download</a></span><span class="op">(</span></span>
<span>  url <span class="op">=</span> <span class="fu">str_c</span><span class="op">(</span><span class="st">"http://www.northwestknowledge.net/metdata/data/pr_2018.nc"</span><span class="op">)</span>,</span>
<span>  destfile <span class="op">=</span> <span class="st">"Data/pr_2018.nc"</span>,</span>
<span>  mode <span class="op">=</span> <span class="st">"wb"</span></span>
<span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>This code should have stored the data as <strong>pr_2018.nc</strong> in the <strong>Data</strong> folder. You can read a netCDF file using <code><a href="https://rspatial.github.io/terra/reference/rast.html">terra::rast()</a></code>.</p>
<div class="cell">
<div class="sourceCode" id="cb66"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="op">(</span></span>
<span>  <span class="va">pr_2018_gm</span> <span class="op">&lt;-</span> <span class="fu">terra</span><span class="fu">::</span><span class="fu"><a href="https://rspatial.github.io/terra/reference/rast.html">rast</a></span><span class="op">(</span><span class="st">"Data/pr_2018.nc"</span><span class="op">)</span></span>
<span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>class       : SpatRaster 
size        : 585, 1386, 365  (nrow, ncol, nlyr)
resolution  : 0.04166667, 0.04166667  (x, y)
extent      : -124.7875, -67.0375, 25.04583, 49.42083  (xmin, xmax, ymin, ymax)
coord. ref. : lon/lat WGS 84 (EPSG:4326) 
source      : pr_2018.nc 
varname     : precipitation_amount (pr) 
names       : preci~43099, preci~43100, preci~43101, preci~43102, preci~43103, preci~43104, ... 
unit        : mm 
depth       : 43099 to 43463 (day [days since 1900-01-01 00:00:00]: 365 steps) </code></pre>
</div>
</div>
<p>You can see that it has 365 layers: one layer per day in 2018. Let’s now look at layer names:</p>
<div class="cell">
<div class="sourceCode" id="cb68"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="va">pr_2018_gm</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "precipitation_amount_day=43099" "precipitation_amount_day=43100"
[3] "precipitation_amount_day=43101" "precipitation_amount_day=43102"
[5] "precipitation_amount_day=43103" "precipitation_amount_day=43104"</code></pre>
</div>
</div>
<p>Since we have 365 layers and the number at the end of the layer names increase by 1, you would think that <strong>n</strong>th layer represents <strong>n</strong>th day of 2018. In this case, you are correct. However, it is always a good practice to confirm what each layer represents without assuming anything. Now, let’s use the <code>ncdf4</code> package, which is built specifically to handle netCDF4 objects.</p>
<div class="cell">
<div class="sourceCode" id="cb70"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="op">(</span></span>
<span>  <span class="va">pr_2018_nc</span> <span class="op">&lt;-</span> <span class="fu">ncdf4</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/ncdf4/man/nc_open.html">nc_open</a></span><span class="op">(</span><span class="st">"Data/pr_2018.nc"</span><span class="op">)</span></span>
<span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>File Data/pr_2018.nc (NC_FORMAT_NETCDF4):

     1 variables (excluding dimension variables):
        unsigned short precipitation_amount[lon,lat,day]   (Chunking: [231,98,61])  (Compression: level 9)
            _FillValue: 32767
            units: mm
            description: Daily Accumulated Precipitation
            long_name: pr
            standard_name: pr
            missing_value: 32767
            dimensions: lon lat time
            grid_mapping: crs
            coordinate_system: WGS84,EPSG:4326
            scale_factor: 0.1
            add_offset: 0
            coordinates: lon lat
            _Unsigned: true

     4 dimensions:
        lon  Size:1386 
            units: degrees_east
            description: longitude
            long_name: longitude
            standard_name: longitude
            axis: X
        lat  Size:585 
            units: degrees_north
            description: latitude
            long_name: latitude
            standard_name: latitude
            axis: Y
        day  Size:365 
            description: days since 1900-01-01
            units: days since 1900-01-01 00:00:00
            long_name: time
            standard_name: time
            calendar: gregorian
        crs  Size:1 
            grid_mapping_name: latitude_longitude
            longitude_of_prime_meridian: 0
            semi_major_axis: 6378137
            long_name: WGS 84
            inverse_flattening: 298.257223563
            GeoTransform: -124.7666666333333 0.041666666666666 0  49.400000000000000 -0.041666666666666
            spatial_ref: GEOGCS["WGS 84",DATUM["WGS_1984",SPHEROID["WGS 84",6378137,298.257223563,AUTHORITY["EPSG","7030"]],AUTHORITY["EPSG","6326"]],PRIMEM["Greenwich",0,AUTHORITY["EPSG","8901"]],UNIT["degree",0.0174532925199433,AUTHORITY["EPSG","9122"]],AUTHORITY["EPSG","4326"]]

    19 global attributes:
        geospatial_bounds_crs: EPSG:4326
        Conventions: CF-1.6
        geospatial_bounds: POLYGON((-124.7666666333333 49.400000000000000, -124.7666666333333 25.066666666666666, -67.058333300000015 25.066666666666666, -67.058333300000015 49.400000000000000, -124.7666666333333 49.400000000000000))
        geospatial_lat_min: 25.066666666666666
        geospatial_lat_max: 49.40000000000000
        geospatial_lon_min: -124.7666666333333
        geospatial_lon_max: -67.058333300000015
        geospatial_lon_resolution: 0.041666666666666
        geospatial_lat_resolution: 0.041666666666666
        geospatial_lat_units: decimal_degrees north
        geospatial_lon_units: decimal_degrees east
        coordinate_system: EPSG:4326
        author: John Abatzoglou - University of Idaho, jabatzoglou@uidaho.edu
        date: 03 May 2021
        note1: The projection information for this file is: GCS WGS 1984.
        note2: Citation: Abatzoglou, J.T., 2013, Development of gridded surface meteorological data for ecological applications and modeling, International Journal of Climatology, DOI: 10.1002/joc.3413
        note3: Data in slices after last_permanent_slice (1-based) are considered provisional and subject to change with subsequent updates
        note4: Data in slices after last_provisional_slice (1-based) are considered early and subject to change with subsequent updates
        note5: Days correspond approximately to calendar days ending at midnight, Mountain Standard Time (7 UTC the next calendar day)</code></pre>
</div>
</div>
<p>As you can see from the output, there is tons of information that we did not see when we read the data using <code>rast()</code>, which includes the explanation of the third dimension (day) of this raster object. It turned out that the numerical values at the end of layer names in the <code>SpatRaster</code> object are <strong>days since 1900-01-01</strong>. So, the first layer (named <strong>precipitation_amount_day=43099</strong>) represents:</p>
<div class="cell">
<div class="sourceCode" id="cb72"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">lubridate</span><span class="fu">::</span><span class="fu"><a href="https://lubridate.tidyverse.org/reference/ymd.html">ymd</a></span><span class="op">(</span><span class="st">"1900-01-01"</span><span class="op">)</span> <span class="op">+</span> <span class="fl">43099</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "2018-01-01"</code></pre>
</div>
</div>
<p>Actually, if we use <code><a href="https://rdrr.io/pkg/raster/man/brick.html">raster::brick()</a></code>, instead of <code><a href="https://rspatial.github.io/terra/reference/rast.html">terra::rast()</a></code>, then we can see the naming convention of the layers:</p>
<div class="cell">
<div class="sourceCode" id="cb74"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="op">(</span></span>
<span>  <span class="va">pr_2018_b</span> <span class="op">&lt;-</span> <span class="fu">raster</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/raster/man/brick.html">brick</a></span><span class="op">(</span><span class="st">"Data/pr_2018.nc"</span><span class="op">)</span></span>
<span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>class      : RasterBrick 
dimensions : 585, 1386, 810810, 365  (nrow, ncol, ncell, nlayers)
resolution : 0.04166667, 0.04166667  (x, y)
extent     : -124.7875, -67.0375, 25.04583, 49.42083  (xmin, xmax, ymin, ymax)
crs        : +proj=longlat +datum=WGS84 +no_defs 
source     : pr_2018.nc 
names      : X43099, X43100, X43101, X43102, X43103, X43104, X43105, X43106, X43107, X43108, X43109, X43110, X43111, X43112, X43113, ... 
day (days since 1900-01-01 00:00:00): 43099, 43463 (min, max)
varname    : precipitation_amount </code></pre>
</div>
</div>
<p><code>SpatRaster</code> or <code>RasterBrick</code> objects are easier to work with as many useful functions accept them as inputs, but not the <code>ncdf4</code> object. Personally, I first scrutinize a netCDFs file using <code>nc_open()</code> and then import it as a <code>SpatRaster</code> or <code>RasterBrick</code> object<a href="#fn7" class="footnote-ref" id="fnref7" role="doc-noteref"><sup>7</sup></a>. Recovering the dates for the layers is particularly important as we often wrangle the resulting data based on date (e.g., subset the data so that you have only April to September). An example of date recovery can be seen in <a href="09-DownloadSpatialData.html#sec-gridMET" class="quarto-xref"><span>Section 8.5</span></a>.</p>
<div class="no-row-height column-margin column-container"><div id="fn7"><p><sup>7</sup>&nbsp;Even though <code>RasterBrick</code> provides the description of how layers are named, I think it is a good practice to see the full description in the <code>ncdf4</code> object.</p></div></div><p>For those who are interested in more detailed descriptions of how to work with <code>ncdf4</code> object is provided <a href="https://pjbartlein.github.io/REarthSysSci/netCDF.html">here</a>.</p>


<!-- -->

</section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
        for (let i=0; i<detailsSrc.length; i++) {
          const details = detailsSrc[i].parentElement;
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/tmieno2\.github\.io\/R-as-GIS-for-Economists\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="../chapters/02-VectorDataBasics.html" class="pagination-link" aria-label="Vector Data Basics with `sf`">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Vector Data Basics with <code>sf</code></span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../chapters/04-SpatialInteractionVectorVector.html" class="pagination-link" aria-label="Spatial Interaction: Vector-Vector">
        <span class="nav-page-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Spatial Interaction: Vector-Vector</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="sourceCode" id="cb76" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a><span class="fu"># Raster Data Basics with `terra` {#sec-raster-basics}</span></span>
<span id="cb76-2"><a href="#cb76-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-5"><a href="#cb76-5" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb76-6"><a href="#cb76-6" aria-hidden="true" tabindex="-1"></a><span class="co">#| eval: false</span></span>
<span id="cb76-7"><a href="#cb76-7" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: false</span></span>
<span id="cb76-8"><a href="#cb76-8" aria-hidden="true" tabindex="-1"></a><span class="co"># This is for debugging the code on the local computer </span></span>
<span id="cb76-9"><a href="#cb76-9" aria-hidden="true" tabindex="-1"></a><span class="fu">setwd</span>(here<span class="sc">::</span><span class="fu">here</span>(<span class="st">"chapters"</span>))</span>
<span id="cb76-10"><a href="#cb76-10" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb76-11"><a href="#cb76-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-14"><a href="#cb76-14" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb76-15"><a href="#cb76-15" aria-hidden="true" tabindex="-1"></a><span class="co">#| include: false</span></span>
<span id="cb76-16"><a href="#cb76-16" aria-hidden="true" tabindex="-1"></a><span class="co">#| cache: false</span></span>
<span id="cb76-17"><a href="#cb76-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-18"><a href="#cb76-18" aria-hidden="true" tabindex="-1"></a><span class="co">#--- load packages ---#</span></span>
<span id="cb76-19"><a href="#cb76-19" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(data.table)</span>
<span id="cb76-20"><a href="#cb76-20" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(stringr)</span>
<span id="cb76-21"><a href="#cb76-21" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(raster)</span>
<span id="cb76-22"><a href="#cb76-22" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(terra)</span>
<span id="cb76-23"><a href="#cb76-23" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyterra)</span>
<span id="cb76-24"><a href="#cb76-24" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lubridate)</span>
<span id="cb76-25"><a href="#cb76-25" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sf)</span>
<span id="cb76-26"><a href="#cb76-26" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tictoc)</span>
<span id="cb76-27"><a href="#cb76-27" aria-hidden="true" tabindex="-1"></a><span class="co"># setwd("/Users/tmieno2/Box/Teaching/AAEA R/GIS")</span></span>
<span id="cb76-28"><a href="#cb76-28" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb76-29"><a href="#cb76-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-30"><a href="#cb76-30" aria-hidden="true" tabindex="-1"></a><span class="fu">## Before you start {-}</span></span>
<span id="cb76-31"><a href="#cb76-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-32"><a href="#cb76-32" aria-hidden="true" tabindex="-1"></a>In this chapter, we will explore how to handle raster data using the <span class="in">`raster`</span> and <span class="in">`terra`</span> packages. The <span class="in">`raster`</span> package has long been the standard for raster data handling, but the <span class="in">`terra`</span> package has now superseded the <span class="in">`raster`</span> package. <span class="in">`terra`</span> typically offers faster performance for many raster operations compared to <span class="in">`raster`</span>. However, we will still cover <span class="in">`raster`</span> object classes and how to convert between <span class="in">`raster`</span> and <span class="in">`terra`</span> objects. This is because many of the existing spatial packages still rely on <span class="in">`raster`</span> object classes and have not yet transitioned to <span class="in">`terra`</span>. Both packages share many function names, and key differences will be clarified as we proceed. </span>
<span id="cb76-33"><a href="#cb76-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-34"><a href="#cb76-34" aria-hidden="true" tabindex="-1"></a>For many scientists, one of the most common and time-consuming raster data task is extracting values for vector data. As such, we will focus on the essential knowledge needed for this process, which will be thoroughly discussed in @sec-int-RV. </span>
<span id="cb76-35"><a href="#cb76-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-36"><a href="#cb76-36" aria-hidden="true" tabindex="-1"></a>Finally, if you frequently work with raster data that includes temporal dimensions (e.g., PRISM, Daymet), you may find the <span class="in">`stars`</span> package useful (covered in @sec-stars-basics). It offers a data model tailored for time-based raster data and allows the use of <span class="in">`dplyr`</span> verbs for data manipulation.</span>
<span id="cb76-37"><a href="#cb76-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-38"><a href="#cb76-38" aria-hidden="true" tabindex="-1"></a><span class="fu">### Direction for replication {-}</span></span>
<span id="cb76-39"><a href="#cb76-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-40"><a href="#cb76-40" aria-hidden="true" tabindex="-1"></a>**Datasets**</span>
<span id="cb76-41"><a href="#cb76-41" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-42"><a href="#cb76-42" aria-hidden="true" tabindex="-1"></a>All the datasets that you need to import are available <span class="co">[</span><span class="ot">here</span><span class="co">](https://www.dropbox.com/sh/yf1u2gcnjyfbw38/AAD-cYgMyGMIP2kih2Jd6rjGa?dl=0)</span>. In this chapter, the path to files is set relative to my own working directory (which is hidden). To run the codes without having to mess with paths to the files, follow these steps:</span>
<span id="cb76-43"><a href="#cb76-43" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-44"><a href="#cb76-44" aria-hidden="true" tabindex="-1"></a><span class="ss">+ </span>set a folder (any folder) as the working directory using <span class="in">`setwd()`</span>  </span>
<span id="cb76-45"><a href="#cb76-45" aria-hidden="true" tabindex="-1"></a><span class="ss">+ </span>create a folder called "Data" inside the folder designated as the working directory (if you have created a "Data" folder previously, skip this step)</span>
<span id="cb76-46"><a href="#cb76-46" aria-hidden="true" tabindex="-1"></a><span class="ss">+ </span>download the pertinent datasets from <span class="co">[</span><span class="ot">here</span><span class="co">](https://www.dropbox.com/sh/yf1u2gcnjyfbw38/AAD-cYgMyGMIP2kih2Jd6rjGa?dl=0)</span> </span>
<span id="cb76-47"><a href="#cb76-47" aria-hidden="true" tabindex="-1"></a><span class="ss">+ </span>place all the files in the downloaded folder in the "Data" folder</span>
<span id="cb76-48"><a href="#cb76-48" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-49"><a href="#cb76-49" aria-hidden="true" tabindex="-1"></a>**Packages**</span>
<span id="cb76-50"><a href="#cb76-50" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-51"><a href="#cb76-51" aria-hidden="true" tabindex="-1"></a>Run the following code to install or load (if already installed) the <span class="in">`pacman`</span> package, and then install or load (if already installed) the listed package inside the <span class="in">`pacman::p_load()`</span> function.</span>
<span id="cb76-52"><a href="#cb76-52" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-53"><a href="#cb76-53" aria-hidden="true" tabindex="-1"></a><span class="in">```{r Chap4_packages}</span></span>
<span id="cb76-54"><a href="#cb76-54" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="sc">!</span><span class="fu">require</span>(<span class="st">"pacman"</span>)) <span class="fu">install.packages</span>(<span class="st">"pacman"</span>)</span>
<span id="cb76-55"><a href="#cb76-55" aria-hidden="true" tabindex="-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(</span>
<span id="cb76-56"><a href="#cb76-56" aria-hidden="true" tabindex="-1"></a>  terra, <span class="co"># handle raster data</span></span>
<span id="cb76-57"><a href="#cb76-57" aria-hidden="true" tabindex="-1"></a>  tidyterra, <span class="co"># handle raster data using dplyr verbs</span></span>
<span id="cb76-58"><a href="#cb76-58" aria-hidden="true" tabindex="-1"></a>  raster, <span class="co"># handle raster data</span></span>
<span id="cb76-59"><a href="#cb76-59" aria-hidden="true" tabindex="-1"></a>  mapview, <span class="co"># create interactive maps</span></span>
<span id="cb76-60"><a href="#cb76-60" aria-hidden="true" tabindex="-1"></a>  dplyr, <span class="co"># data wrangling</span></span>
<span id="cb76-61"><a href="#cb76-61" aria-hidden="true" tabindex="-1"></a>  sf, <span class="co"># vector data handling</span></span>
<span id="cb76-62"><a href="#cb76-62" aria-hidden="true" tabindex="-1"></a>  lubridate <span class="co"># date handling</span></span>
<span id="cb76-63"><a href="#cb76-63" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb76-64"><a href="#cb76-64" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb76-65"><a href="#cb76-65" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-68"><a href="#cb76-68" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb76-69"><a href="#cb76-69" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: false</span></span>
<span id="cb76-70"><a href="#cb76-70" aria-hidden="true" tabindex="-1"></a><span class="co">#| eval: false</span></span>
<span id="cb76-71"><a href="#cb76-71" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-72"><a href="#cb76-72" aria-hidden="true" tabindex="-1"></a><span class="co"># This code is for obtaining data used in the chapter</span></span>
<span id="cb76-73"><a href="#cb76-73" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-74"><a href="#cb76-74" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(CropScapeR)</span>
<span id="cb76-75"><a href="#cb76-75" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-76"><a href="#cb76-76" aria-hidden="true" tabindex="-1"></a>IA_cdl_2015 <span class="ot">&lt;-</span></span>
<span id="cb76-77"><a href="#cb76-77" aria-hidden="true" tabindex="-1"></a>  CropScapeR<span class="sc">::</span><span class="fu">GetCDLData</span>(</span>
<span id="cb76-78"><a href="#cb76-78" aria-hidden="true" tabindex="-1"></a>    <span class="at">aoi =</span> <span class="dv">19</span>,</span>
<span id="cb76-79"><a href="#cb76-79" aria-hidden="true" tabindex="-1"></a>    <span class="at">year =</span> <span class="st">"2015"</span>,</span>
<span id="cb76-80"><a href="#cb76-80" aria-hidden="true" tabindex="-1"></a>    <span class="at">type =</span> <span class="st">"f"</span></span>
<span id="cb76-81"><a href="#cb76-81" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb76-82"><a href="#cb76-82" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-83"><a href="#cb76-83" aria-hidden="true" tabindex="-1"></a>IA_cdl_2016 <span class="ot">&lt;-</span></span>
<span id="cb76-84"><a href="#cb76-84" aria-hidden="true" tabindex="-1"></a>  CropScapeR<span class="sc">::</span><span class="fu">GetCDLData</span>(</span>
<span id="cb76-85"><a href="#cb76-85" aria-hidden="true" tabindex="-1"></a>    <span class="at">aoi =</span> <span class="dv">19</span>,</span>
<span id="cb76-86"><a href="#cb76-86" aria-hidden="true" tabindex="-1"></a>    <span class="at">year =</span> <span class="st">"2016"</span>,</span>
<span id="cb76-87"><a href="#cb76-87" aria-hidden="true" tabindex="-1"></a>    <span class="at">type =</span> <span class="st">"f"</span></span>
<span id="cb76-88"><a href="#cb76-88" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb76-89"><a href="#cb76-89" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-90"><a href="#cb76-90" aria-hidden="true" tabindex="-1"></a>terra<span class="sc">::</span><span class="fu">writeRaster</span>(IA_cdl_2015, <span class="fu">here</span>(<span class="st">"Data/IA_cdl_2015.tif"</span>), <span class="at">overwrite =</span> <span class="cn">TRUE</span>)</span>
<span id="cb76-91"><a href="#cb76-91" aria-hidden="true" tabindex="-1"></a>terra<span class="sc">::</span><span class="fu">writeRaster</span>(IA_cdl_2016, <span class="fu">here</span>(<span class="st">"Data/IA_cdl_2016.tif"</span>), <span class="at">overwrite =</span> <span class="cn">TRUE</span>)</span>
<span id="cb76-92"><a href="#cb76-92" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb76-93"><a href="#cb76-93" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-94"><a href="#cb76-94" aria-hidden="true" tabindex="-1"></a><span class="fu">## Raster data object classes</span></span>
<span id="cb76-95"><a href="#cb76-95" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-96"><a href="#cb76-96" aria-hidden="true" tabindex="-1"></a><span class="fu">### `raster` package: `RasterLayer`, `RasterStack`, and `RasterBrick`</span></span>
<span id="cb76-97"><a href="#cb76-97" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-98"><a href="#cb76-98" aria-hidden="true" tabindex="-1"></a>Let's start with taking a look at raster data. We will use the CDL data for Iowa in 2015. We can use <span class="in">`raster::raster()`</span> to read a raster data file.</span>
<span id="cb76-99"><a href="#cb76-99" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-100"><a href="#cb76-100" aria-hidden="true" tabindex="-1"></a><span class="in">```{r read_the_IA_cdl_data_run}</span></span>
<span id="cb76-101"><a href="#cb76-101" aria-hidden="true" tabindex="-1"></a><span class="co">#| cache: false</span></span>
<span id="cb76-102"><a href="#cb76-102" aria-hidden="true" tabindex="-1"></a>(</span>
<span id="cb76-103"><a href="#cb76-103" aria-hidden="true" tabindex="-1"></a>  IA_cdl_2015 <span class="ot">&lt;-</span> raster<span class="sc">::</span><span class="fu">raster</span>(<span class="st">"Data/IA_cdl_2015.tif"</span>)</span>
<span id="cb76-104"><a href="#cb76-104" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb76-105"><a href="#cb76-105" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb76-106"><a href="#cb76-106" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-107"><a href="#cb76-107" aria-hidden="true" tabindex="-1"></a>Evaluating an imported raster object provides key information about the raster data, such as its dimensions (number of cells, rows, and columns), spatial resolution (e.g., 30 meters by 30 meters for this dataset), extent, coordinate reference system (CRS), and the minimum and maximum values recorded. The downloaded data is of the class <span class="in">`RasterLayer`</span>, which is defined by the raster package. A <span class="in">`RasterLayer`</span> contains only one layer, meaning that the raster cells hold the value of a single variable (in this case, the land use category code as an integer)</span>
<span id="cb76-108"><a href="#cb76-108" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-109"><a href="#cb76-109" aria-hidden="true" tabindex="-1"></a>---</span>
<span id="cb76-110"><a href="#cb76-110" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-111"><a href="#cb76-111" aria-hidden="true" tabindex="-1"></a>You can stack multiple raster layers of the **same spatial resolution and extent** to create a <span class="in">`RasterStack`</span> using <span class="in">`raster::stack()`</span> or <span class="in">`RasterBrick`</span> using <span class="in">`raster::brick()`</span>. Often times, processing a multi-layer object has computational advantages over processing multiple single-layer one by one^<span class="co">[</span><span class="ot">You will see this in @sec-int-RV where we learn how to extract values from a raster layer for a vector data.</span><span class="co">]</span>. </span>
<span id="cb76-112"><a href="#cb76-112" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-113"><a href="#cb76-113" aria-hidden="true" tabindex="-1"></a>To create a RasterStack and RasterBrick, let's load the CDL data for IA in 2016 and stack it with the 2015 data.</span>
<span id="cb76-114"><a href="#cb76-114" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-115"><a href="#cb76-115" aria-hidden="true" tabindex="-1"></a><span class="in">```{r make_stack_run}</span></span>
<span id="cb76-116"><a href="#cb76-116" aria-hidden="true" tabindex="-1"></a><span class="co">#| cache: false</span></span>
<span id="cb76-117"><a href="#cb76-117" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-118"><a href="#cb76-118" aria-hidden="true" tabindex="-1"></a>IA_cdl_2016 <span class="ot">&lt;-</span> raster<span class="sc">::</span><span class="fu">raster</span>(<span class="st">"Data/IA_cdl_2016.tif"</span>)</span>
<span id="cb76-119"><a href="#cb76-119" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-120"><a href="#cb76-120" aria-hidden="true" tabindex="-1"></a><span class="co">#--- stack the two ---#</span></span>
<span id="cb76-121"><a href="#cb76-121" aria-hidden="true" tabindex="-1"></a>(</span>
<span id="cb76-122"><a href="#cb76-122" aria-hidden="true" tabindex="-1"></a>  IA_cdl_stack <span class="ot">&lt;-</span> raster<span class="sc">::</span><span class="fu">stack</span>(IA_cdl_2015, IA_cdl_2016)</span>
<span id="cb76-123"><a href="#cb76-123" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb76-124"><a href="#cb76-124" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb76-125"><a href="#cb76-125" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-126"><a href="#cb76-126" aria-hidden="true" tabindex="-1"></a><span class="in">`IA_cdl_stack`</span> is of class <span class="in">`RasterStack`</span>, and it has two layers of variables: CDL for 2015 and 2016. You can make it a <span class="in">`RasterBrick`</span> using <span class="in">`raster::brick()`</span>:</span>
<span id="cb76-127"><a href="#cb76-127" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-128"><a href="#cb76-128" aria-hidden="true" tabindex="-1"></a><span class="in">```{r make-brick, eval = F}</span></span>
<span id="cb76-129"><a href="#cb76-129" aria-hidden="true" tabindex="-1"></a><span class="co">#--- stack the two ---#</span></span>
<span id="cb76-130"><a href="#cb76-130" aria-hidden="true" tabindex="-1"></a>IA_cdl_brick <span class="ot">&lt;-</span> <span class="fu">brick</span>(IA_cdl_stack)</span>
<span id="cb76-131"><a href="#cb76-131" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-132"><a href="#cb76-132" aria-hidden="true" tabindex="-1"></a><span class="co">#--- or this works as well ---#</span></span>
<span id="cb76-133"><a href="#cb76-133" aria-hidden="true" tabindex="-1"></a><span class="co"># IA_cdl_brick &lt;- brick(IA_cdl_2015, IA_cdl_2016)</span></span>
<span id="cb76-134"><a href="#cb76-134" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-135"><a href="#cb76-135" aria-hidden="true" tabindex="-1"></a><span class="co">#--- take a look ---#</span></span>
<span id="cb76-136"><a href="#cb76-136" aria-hidden="true" tabindex="-1"></a>IA_cdl_brick</span>
<span id="cb76-137"><a href="#cb76-137" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb76-138"><a href="#cb76-138" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-139"><a href="#cb76-139" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, echo = F}</span></span>
<span id="cb76-140"><a href="#cb76-140" aria-hidden="true" tabindex="-1"></a><span class="co"># saveRDS(IA_cdl_brick, "Data/IA_cdl_brick.rds")</span></span>
<span id="cb76-141"><a href="#cb76-141" aria-hidden="true" tabindex="-1"></a>(</span>
<span id="cb76-142"><a href="#cb76-142" aria-hidden="true" tabindex="-1"></a>IA_cdl_brick <span class="ot">&lt;-</span> <span class="fu">readRDS</span>(<span class="st">"Data/IA_cdl_brick.rds"</span>)</span>
<span id="cb76-143"><a href="#cb76-143" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb76-144"><a href="#cb76-144" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb76-145"><a href="#cb76-145" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-146"><a href="#cb76-146" aria-hidden="true" tabindex="-1"></a>You probably noticed that it took some time to create the <span class="in">`RasterBrick`</span> object^<span class="co">[</span><span class="ot">Read [here](https://geocompr.robinlovelace.net/spatial-class.html#raster-classes) for the difference between `RasterStack` and `RasterBrick`</span><span class="co">]</span>. While spatial operations on <span class="in">`RasterBrick`</span> are supposedly faster than <span class="in">`RasterStack`</span>, the time to create a <span class="in">`RasterBrick`</span> object itself is often long enough to kill the speed advantage entirely. Often, the three raster object types are collectively referred to as <span class="in">`Raster`</span>$^*$ objects for shorthand in the documentation of the <span class="in">`raster`</span> and other related packages.</span>
<span id="cb76-147"><a href="#cb76-147" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-148"><a href="#cb76-148" aria-hidden="true" tabindex="-1"></a><span class="fu">### `terra` package: `SpatRaster`</span></span>
<span id="cb76-149"><a href="#cb76-149" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-150"><a href="#cb76-150" aria-hidden="true" tabindex="-1"></a><span class="in">`terra`</span> package has only one object class for raster data, <span class="in">`SpatRaster`</span> and no distinctions between one-layer and multi-layer rasters is necessary. Let's first convert a <span class="in">`RasterLayer`</span> to a <span class="in">`SpatRaster`</span> using <span class="in">`terra::rast()`</span> function.</span>
<span id="cb76-151"><a href="#cb76-151" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-152"><a href="#cb76-152" aria-hidden="true" tabindex="-1"></a><span class="in">```{r spat_raster, dependson = "read_the_IA_cdl_data", cache = F}</span></span>
<span id="cb76-153"><a href="#cb76-153" aria-hidden="true" tabindex="-1"></a><span class="co">#--- convert to a SpatRaster ---#</span></span>
<span id="cb76-154"><a href="#cb76-154" aria-hidden="true" tabindex="-1"></a>IA_cdl_2015_sr <span class="ot">&lt;-</span> terra<span class="sc">::</span><span class="fu">rast</span>(IA_cdl_2015)</span>
<span id="cb76-155"><a href="#cb76-155" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-156"><a href="#cb76-156" aria-hidden="true" tabindex="-1"></a><span class="co">#--- take a look ---#</span></span>
<span id="cb76-157"><a href="#cb76-157" aria-hidden="true" tabindex="-1"></a>IA_cdl_2015_sr</span>
<span id="cb76-158"><a href="#cb76-158" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb76-159"><a href="#cb76-159" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-160"><a href="#cb76-160" aria-hidden="true" tabindex="-1"></a>You can see that the number of layers (<span class="in">`nlyr`</span> in dimensions) is $1$ because the original object is a <span class="in">`RasterLayer`</span>, which by definition has only one layer. Now, let's convert a <span class="in">`RasterStack`</span> to a <span class="in">`SpatRaster`</span> using <span class="in">`terra::rast()`</span>.  </span>
<span id="cb76-161"><a href="#cb76-161" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-162"><a href="#cb76-162" aria-hidden="true" tabindex="-1"></a><span class="in">```{r spat_raster_nl, cache = F}</span></span>
<span id="cb76-163"><a href="#cb76-163" aria-hidden="true" tabindex="-1"></a><span class="co">#--- convert to a SpatRaster ---#</span></span>
<span id="cb76-164"><a href="#cb76-164" aria-hidden="true" tabindex="-1"></a>IA_cdl_stack_sr <span class="ot">&lt;-</span> terra<span class="sc">::</span><span class="fu">rast</span>(IA_cdl_stack)</span>
<span id="cb76-165"><a href="#cb76-165" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-166"><a href="#cb76-166" aria-hidden="true" tabindex="-1"></a><span class="co">#--- take a look ---#</span></span>
<span id="cb76-167"><a href="#cb76-167" aria-hidden="true" tabindex="-1"></a>IA_cdl_stack_sr</span>
<span id="cb76-168"><a href="#cb76-168" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb76-169"><a href="#cb76-169" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-170"><a href="#cb76-170" aria-hidden="true" tabindex="-1"></a>Again, it is a <span class="in">`SpatRaster`</span>, and you now see that the number of layers is 2. We just confirmed that <span class="in">`terra`</span> has only one class for raster data whether it is single-layer or multiple-layer ones.</span>
<span id="cb76-171"><a href="#cb76-171" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-172"><a href="#cb76-172" aria-hidden="true" tabindex="-1"></a>In order to make multi-layer <span class="in">`SpatRaster`</span> from multiple single-layer <span class="in">`SpatRaster`</span> you can just use <span class="in">`c()`</span> like below:</span>
<span id="cb76-173"><a href="#cb76-173" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-174"><a href="#cb76-174" aria-hidden="true" tabindex="-1"></a><span class="in">```{r echo = F, cache = F}</span></span>
<span id="cb76-175"><a href="#cb76-175" aria-hidden="true" tabindex="-1"></a><span class="co"># Keep getting this error below in SR-concatenate, so a work around:</span></span>
<span id="cb76-176"><a href="#cb76-176" aria-hidden="true" tabindex="-1"></a><span class="co"># Error in x@ptr$combineSources(i@ptr) : external pointer is not valid</span></span>
<span id="cb76-177"><a href="#cb76-177" aria-hidden="true" tabindex="-1"></a>IA_cdl_2015_sr <span class="ot">&lt;-</span> <span class="fu">rast</span>(<span class="st">"Data/IA_cdl_2015.tif"</span>)</span>
<span id="cb76-178"><a href="#cb76-178" aria-hidden="true" tabindex="-1"></a>IA_cdl_2016_sr <span class="ot">&lt;-</span> <span class="fu">rast</span>(<span class="st">"Data/IA_cdl_2016.tif"</span>)</span>
<span id="cb76-179"><a href="#cb76-179" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb76-180"><a href="#cb76-180" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-181"><a href="#cb76-181" aria-hidden="true" tabindex="-1"></a><span class="in">```{r SR-concatenate, cache = F}</span></span>
<span id="cb76-182"><a href="#cb76-182" aria-hidden="true" tabindex="-1"></a><span class="co">#--- create a single-layer SpatRaster ---#</span></span>
<span id="cb76-183"><a href="#cb76-183" aria-hidden="true" tabindex="-1"></a>IA_cdl_2016_sr <span class="ot">&lt;-</span> terra<span class="sc">::</span><span class="fu">rast</span>(IA_cdl_2016)</span>
<span id="cb76-184"><a href="#cb76-184" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-185"><a href="#cb76-185" aria-hidden="true" tabindex="-1"></a><span class="co">#--- concatenate ---#</span></span>
<span id="cb76-186"><a href="#cb76-186" aria-hidden="true" tabindex="-1"></a>(</span>
<span id="cb76-187"><a href="#cb76-187" aria-hidden="true" tabindex="-1"></a>  IA_cdl_ml_sr <span class="ot">&lt;-</span> <span class="fu">c</span>(IA_cdl_2015_sr, IA_cdl_2016_sr)</span>
<span id="cb76-188"><a href="#cb76-188" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb76-189"><a href="#cb76-189" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb76-190"><a href="#cb76-190" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-191"><a href="#cb76-191" aria-hidden="true" tabindex="-1"></a><span class="fu">### Converting a `SpatRaster` object to a `Raster`$^*$ object.</span></span>
<span id="cb76-192"><a href="#cb76-192" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-193"><a href="#cb76-193" aria-hidden="true" tabindex="-1"></a>You can convert a <span class="in">`SpatRaster`</span> object to a <span class="in">`Raster`</span>$^*$ object using <span class="in">`raster::raster()`</span>, <span class="in">`raster::stack()`</span>, and <span class="in">`raster::brick()`</span>. Keep in mind that if you use <span class="in">`raster::rater()`</span> even though <span class="in">`SpatRaster`</span> has multiple layers, the resulting <span class="in">`RasterLayer`</span> object has only the first of the multiple layers. </span>
<span id="cb76-194"><a href="#cb76-194" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-195"><a href="#cb76-195" aria-hidden="true" tabindex="-1"></a><span class="in">```{r convert_back}</span></span>
<span id="cb76-196"><a href="#cb76-196" aria-hidden="true" tabindex="-1"></a><span class="co">#--- RasterLayer (only 1st layer) ---#</span></span>
<span id="cb76-197"><a href="#cb76-197" aria-hidden="true" tabindex="-1"></a>IA_cdl_stack_sr <span class="sc">%&gt;%</span> raster<span class="sc">::</span><span class="fu">raster</span>()</span>
<span id="cb76-198"><a href="#cb76-198" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-199"><a href="#cb76-199" aria-hidden="true" tabindex="-1"></a><span class="co">#--- RasterLayer ---#</span></span>
<span id="cb76-200"><a href="#cb76-200" aria-hidden="true" tabindex="-1"></a>IA_cdl_stack_sr <span class="sc">%&gt;%</span> raster<span class="sc">::</span><span class="fu">stack</span>()</span>
<span id="cb76-201"><a href="#cb76-201" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-202"><a href="#cb76-202" aria-hidden="true" tabindex="-1"></a><span class="co">#--- RasterLayer (this takes some time) ---#</span></span>
<span id="cb76-203"><a href="#cb76-203" aria-hidden="true" tabindex="-1"></a>IA_cdl_stack_sr <span class="sc">%&gt;%</span> raster<span class="sc">::</span><span class="fu">brick</span>()</span>
<span id="cb76-204"><a href="#cb76-204" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb76-205"><a href="#cb76-205" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-206"><a href="#cb76-206" aria-hidden="true" tabindex="-1"></a>Instead of these functions, you can simply use <span class="in">`as(SpatRast, "Raster")`</span> like below:</span>
<span id="cb76-207"><a href="#cb76-207" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-208"><a href="#cb76-208" aria-hidden="true" tabindex="-1"></a><span class="in">```{r }</span></span>
<span id="cb76-209"><a href="#cb76-209" aria-hidden="true" tabindex="-1"></a><span class="fu">as</span>(IA_cdl_stack_sr, <span class="st">"Raster"</span>)</span>
<span id="cb76-210"><a href="#cb76-210" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb76-211"><a href="#cb76-211" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-212"><a href="#cb76-212" aria-hidden="true" tabindex="-1"></a>This works for any <span class="in">`Raster`</span>$^*$ object and you do not have to pick the right function like above.</span>
<span id="cb76-213"><a href="#cb76-213" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-214"><a href="#cb76-214" aria-hidden="true" tabindex="-1"></a><span class="fu">### Vector data in the `terra` package</span></span>
<span id="cb76-215"><a href="#cb76-215" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-216"><a href="#cb76-216" aria-hidden="true" tabindex="-1"></a><span class="in">`terra`</span> package has its own class for vector data, called <span class="in">`SpatVector`</span>. While we do not use any of the vector data functionality provided by the <span class="in">`terra`</span> package, we learn how to convert an <span class="in">`sf`</span> object to <span class="in">`SpatVector`</span> because some of the <span class="in">`terra`</span> functions do not support <span class="in">`sf`</span> as of now (this will likely be resolved very soon). We will see some use cases of this conversion in @sec-int-RV when we learn raster value extractions for vector data using <span class="in">`terra::extract()`</span>. </span>
<span id="cb76-217"><a href="#cb76-217" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-218"><a href="#cb76-218" aria-hidden="true" tabindex="-1"></a>As an example, let's use Illinois county border data. </span>
<span id="cb76-219"><a href="#cb76-219" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-220"><a href="#cb76-220" aria-hidden="true" tabindex="-1"></a><span class="in">```{r il_county_echo}</span></span>
<span id="cb76-221"><a href="#cb76-221" aria-hidden="true" tabindex="-1"></a><span class="co">#| cache: true</span></span>
<span id="cb76-222"><a href="#cb76-222" aria-hidden="true" tabindex="-1"></a><span class="co">#--- Illinois county boundary ---#</span></span>
<span id="cb76-223"><a href="#cb76-223" aria-hidden="true" tabindex="-1"></a>(</span>
<span id="cb76-224"><a href="#cb76-224" aria-hidden="true" tabindex="-1"></a>  IL_county <span class="ot">&lt;-</span> </span>
<span id="cb76-225"><a href="#cb76-225" aria-hidden="true" tabindex="-1"></a>    tigris<span class="sc">::</span><span class="fu">counties</span>(</span>
<span id="cb76-226"><a href="#cb76-226" aria-hidden="true" tabindex="-1"></a>      <span class="at">state =</span> <span class="st">"Illinois"</span>, </span>
<span id="cb76-227"><a href="#cb76-227" aria-hidden="true" tabindex="-1"></a>      <span class="at">progress_bar =</span> <span class="cn">FALSE</span></span>
<span id="cb76-228"><a href="#cb76-228" aria-hidden="true" tabindex="-1"></a>    ) <span class="sc">%&gt;%</span></span>
<span id="cb76-229"><a href="#cb76-229" aria-hidden="true" tabindex="-1"></a>    dplyr<span class="sc">::</span><span class="fu">select</span>(STATEFP, COUNTYFP)</span>
<span id="cb76-230"><a href="#cb76-230" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb76-231"><a href="#cb76-231" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb76-232"><a href="#cb76-232" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-233"><a href="#cb76-233" aria-hidden="true" tabindex="-1"></a>You can convert an <span class="in">`sf`</span> object to <span class="in">`SpatVector`</span> object using <span class="in">`terra::vect()`</span>.</span>
<span id="cb76-234"><a href="#cb76-234" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-235"><a href="#cb76-235" aria-hidden="true" tabindex="-1"></a><span class="in">```{r to_sv}</span></span>
<span id="cb76-236"><a href="#cb76-236" aria-hidden="true" tabindex="-1"></a>(</span>
<span id="cb76-237"><a href="#cb76-237" aria-hidden="true" tabindex="-1"></a>  IL_county_sv <span class="ot">&lt;-</span> terra<span class="sc">::</span><span class="fu">vect</span>(IL_county)</span>
<span id="cb76-238"><a href="#cb76-238" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb76-239"><a href="#cb76-239" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb76-240"><a href="#cb76-240" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-241"><a href="#cb76-241" aria-hidden="true" tabindex="-1"></a><span class="fu">## Read and write a raster data file</span></span>
<span id="cb76-242"><a href="#cb76-242" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-243"><a href="#cb76-243" aria-hidden="true" tabindex="-1"></a>Raster data files can come in numerous different formats. For example, PRPISM comes in the Band Interleaved by Line (BIL) format, some of the Daymet data comes in netCDF format. Other popular formats include GeoTiff, SAGA, ENVI, and many others. </span>
<span id="cb76-244"><a href="#cb76-244" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-245"><a href="#cb76-245" aria-hidden="true" tabindex="-1"></a><span class="fu">### Read raster file(s)</span></span>
<span id="cb76-246"><a href="#cb76-246" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-247"><a href="#cb76-247" aria-hidden="true" tabindex="-1"></a>You can use <span class="in">`terra::rast()`</span> to read raster data in many common formats, and in most cases, this function will work for your raster data. In this example, we read a GeoTIFF file (with a .tif extension).</span>
<span id="cb76-248"><a href="#cb76-248" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-249"><a href="#cb76-249" aria-hidden="true" tabindex="-1"></a><span class="in">```{r read_no_eval_terra, cache  =F}</span></span>
<span id="cb76-250"><a href="#cb76-250" aria-hidden="true" tabindex="-1"></a>(</span>
<span id="cb76-251"><a href="#cb76-251" aria-hidden="true" tabindex="-1"></a>  IA_cdl_2015_sr <span class="ot">&lt;-</span> terra<span class="sc">::</span><span class="fu">rast</span>(<span class="st">"Data/IA_cdl_2015.tif"</span>)</span>
<span id="cb76-252"><a href="#cb76-252" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb76-253"><a href="#cb76-253" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb76-254"><a href="#cb76-254" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-255"><a href="#cb76-255" aria-hidden="true" tabindex="-1"></a>You can read multiple single-layer raster datasets of the same spatial extent and resolution at the same time to have a multi-layer <span class="in">`SpatRaster`</span> object. Here, we import two single-layer raster datasets (IA_cdl_2015.tif and IA_cdl_2016.tif) to create a two-layer <span class="in">`SpatRaster`</span> object.</span>
<span id="cb76-256"><a href="#cb76-256" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-257"><a href="#cb76-257" aria-hidden="true" tabindex="-1"></a><span class="in">```{r multiple_files}</span></span>
<span id="cb76-258"><a href="#cb76-258" aria-hidden="true" tabindex="-1"></a><span class="co">#--- the list of path to the files ---#</span></span>
<span id="cb76-259"><a href="#cb76-259" aria-hidden="true" tabindex="-1"></a>files_list <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Data/IA_cdl_2015.tif"</span>, <span class="st">"Data/IA_cdl_2016.tif"</span>)</span>
<span id="cb76-260"><a href="#cb76-260" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-261"><a href="#cb76-261" aria-hidden="true" tabindex="-1"></a><span class="co">#--- read the two at the same time ---#</span></span>
<span id="cb76-262"><a href="#cb76-262" aria-hidden="true" tabindex="-1"></a>(</span>
<span id="cb76-263"><a href="#cb76-263" aria-hidden="true" tabindex="-1"></a>  multi_layer_sr <span class="ot">&lt;-</span> terra<span class="sc">::</span><span class="fu">rast</span>(files_list)</span>
<span id="cb76-264"><a href="#cb76-264" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb76-265"><a href="#cb76-265" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb76-266"><a href="#cb76-266" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-267"><a href="#cb76-267" aria-hidden="true" tabindex="-1"></a>Of course, this only works because the two datasets have the identical spatial extent and resolution. There are, however, no restrictions on what variable each of the raster layers represent. For example, you can combine PRISM temperature and precipitation raster layers if you want.</span>
<span id="cb76-268"><a href="#cb76-268" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-269"><a href="#cb76-269" aria-hidden="true" tabindex="-1"></a><span class="fu">### Write raster files</span></span>
<span id="cb76-270"><a href="#cb76-270" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-271"><a href="#cb76-271" aria-hidden="true" tabindex="-1"></a>You can write a <span class="in">`SpatRaster`</span> object using <span class="in">`terra::writeRaster()`</span>.</span>
<span id="cb76-272"><a href="#cb76-272" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-273"><a href="#cb76-273" aria-hidden="true" tabindex="-1"></a><span class="in">```{r write_terra}</span></span>
<span id="cb76-274"><a href="#cb76-274" aria-hidden="true" tabindex="-1"></a><span class="co">#| eval: false</span></span>
<span id="cb76-275"><a href="#cb76-275" aria-hidden="true" tabindex="-1"></a>terra<span class="sc">::</span><span class="fu">writeRaster</span>(IA_cdl_2015_sr, <span class="st">"Data/IA_cdl_stack.tif"</span>, <span class="at">filetype =</span> <span class="st">"GTiff"</span>, <span class="at">overwrite =</span> <span class="cn">TRUE</span>)</span>
<span id="cb76-276"><a href="#cb76-276" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb76-277"><a href="#cb76-277" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-278"><a href="#cb76-278" aria-hidden="true" tabindex="-1"></a>The above code saves <span class="in">`IA_cdl_2015_sr`</span> (a <span class="in">`SpatRaster`</span> object) as a GeoTiff file.^<span class="co">[</span><span class="ot">There are many other alternative formats (see [here](https://www.rdocumentation.org/packages/raster/versions/3.0-12/topics/writeRaster))</span><span class="co">]</span> The filetype option can be dropped as <span class="in">`writeRaster()`</span> infers the filetype from the extension of the file name. The <span class="in">`overwrite = TRUE`</span> option is necessary if a file with the same name already exists and you are overwriting it. This is one of the many areas <span class="in">`terra`</span> is better than <span class="in">`raster`</span>. <span class="in">`raster::writeRaster()`</span> can be frustratingly slow for a large <span class="in">`Raster`</span>$^*$ object. <span class="in">`terra::writeRaster()`</span> is much faster.</span>
<span id="cb76-279"><a href="#cb76-279" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-280"><a href="#cb76-280" aria-hidden="true" tabindex="-1"></a>You can also save a multi-layer <span class="in">`SpatRaster`</span> object just like you save a single-layer <span class="in">`SpatRaster`</span> object. </span>
<span id="cb76-281"><a href="#cb76-281" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-282"><a href="#cb76-282" aria-hidden="true" tabindex="-1"></a><span class="in">```{r write_terra_2}</span></span>
<span id="cb76-283"><a href="#cb76-283" aria-hidden="true" tabindex="-1"></a><span class="co">#| eval: false</span></span>
<span id="cb76-284"><a href="#cb76-284" aria-hidden="true" tabindex="-1"></a>terra<span class="sc">::</span><span class="fu">writeRaster</span>(IA_cdl_stack_sr, <span class="st">"Data/IA_cdl_stack.tif"</span>, <span class="at">filetype =</span> <span class="st">"GTiff"</span>, <span class="at">overwrite =</span> <span class="cn">TRUE</span>)</span>
<span id="cb76-285"><a href="#cb76-285" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb76-286"><a href="#cb76-286" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-287"><a href="#cb76-287" aria-hidden="true" tabindex="-1"></a>The saved file is a multi-band raster datasets. So, if you have many raster files of the same spatial extent and resolution, you can "stack" them on R and then export it to a single multi-band raster datasets, which cleans up your data folder.</span>
<span id="cb76-288"><a href="#cb76-288" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb76-289"><a href="#cb76-289" aria-hidden="true" tabindex="-1"></a><span class="fu">## Basic operations</span></span>
<span id="cb76-290"><a href="#cb76-290" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-291"><a href="#cb76-291" aria-hidden="true" tabindex="-1"></a><span class="fu">### Accessing the metadata</span></span>
<span id="cb76-292"><a href="#cb76-292" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-293"><a href="#cb76-293" aria-hidden="true" tabindex="-1"></a><span class="fu">#### Extent and dimensions</span></span>
<span id="cb76-294"><a href="#cb76-294" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-295"><a href="#cb76-295" aria-hidden="true" tabindex="-1"></a>The spatial extent of a <span class="in">`SpatRaster`</span> object is like a bouding box for an <span class="in">`sf`</span> object. It can be used to crop a <span class="in">`SpatRaster`</span> or <span class="in">`sf`</span> object.</span>
<span id="cb76-296"><a href="#cb76-296" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-299"><a href="#cb76-299" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb76-300"><a href="#cb76-300" aria-hidden="true" tabindex="-1"></a>terra<span class="sc">::</span><span class="fu">ext</span>(IA_cdl_ml_sr)</span>
<span id="cb76-301"><a href="#cb76-301" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb76-302"><a href="#cb76-302" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-303"><a href="#cb76-303" aria-hidden="true" tabindex="-1"></a>You can access the dimensions of a <span class="in">`SpatRaster`</span> object as follows: </span>
<span id="cb76-304"><a href="#cb76-304" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-307"><a href="#cb76-307" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb76-308"><a href="#cb76-308" aria-hidden="true" tabindex="-1"></a><span class="co">#--- number of columns ---#</span></span>
<span id="cb76-309"><a href="#cb76-309" aria-hidden="true" tabindex="-1"></a>terra<span class="sc">::</span><span class="fu">ncol</span>(IA_cdl_ml_sr)</span>
<span id="cb76-310"><a href="#cb76-310" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-311"><a href="#cb76-311" aria-hidden="true" tabindex="-1"></a><span class="co">#--- number of rows ---#</span></span>
<span id="cb76-312"><a href="#cb76-312" aria-hidden="true" tabindex="-1"></a>terra<span class="sc">::</span><span class="fu">nrow</span>(IA_cdl_ml_sr)</span>
<span id="cb76-313"><a href="#cb76-313" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-314"><a href="#cb76-314" aria-hidden="true" tabindex="-1"></a><span class="co">#--- number of layers ---#</span></span>
<span id="cb76-315"><a href="#cb76-315" aria-hidden="true" tabindex="-1"></a>terra<span class="sc">::</span><span class="fu">nlyr</span>(IA_cdl_ml_sr)</span>
<span id="cb76-316"><a href="#cb76-316" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-317"><a href="#cb76-317" aria-hidden="true" tabindex="-1"></a><span class="co">#--- number of cells ---#</span></span>
<span id="cb76-318"><a href="#cb76-318" aria-hidden="true" tabindex="-1"></a>terra<span class="sc">::</span><span class="fu">ncell</span>(IA_cdl_ml_sr) </span>
<span id="cb76-319"><a href="#cb76-319" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb76-320"><a href="#cb76-320" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-321"><a href="#cb76-321" aria-hidden="true" tabindex="-1"></a><span class="fu">#### Get CRS</span></span>
<span id="cb76-322"><a href="#cb76-322" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-323"><a href="#cb76-323" aria-hidden="true" tabindex="-1"></a>You often need to extract the CRS of a raster object before you interact it with vector data (e.g., extracting values from a raster layer to vector data, or cropping a raster layer to the spatial extent of vector data), which can be done using <span class="in">`terra::crs()`</span>: </span>
<span id="cb76-324"><a href="#cb76-324" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-325"><a href="#cb76-325" aria-hidden="true" tabindex="-1"></a><span class="in">```{r get_crs_terra}</span></span>
<span id="cb76-326"><a href="#cb76-326" aria-hidden="true" tabindex="-1"></a>terra<span class="sc">::</span><span class="fu">crs</span>(IA_cdl_ml_sr)</span>
<span id="cb76-327"><a href="#cb76-327" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb76-328"><a href="#cb76-328" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-329"><a href="#cb76-329" aria-hidden="true" tabindex="-1"></a><span class="fu">### Get cell values</span></span>
<span id="cb76-330"><a href="#cb76-330" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-331"><a href="#cb76-331" aria-hidden="true" tabindex="-1"></a>You can access the values stored in a <span class="in">`SpatRaster`</span> object using the <span class="in">`terra::values()`</span> function or <span class="in">`[]`</span>:</span>
<span id="cb76-332"><a href="#cb76-332" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-333"><a href="#cb76-333" aria-hidden="true" tabindex="-1"></a>**`terra::values()`**</span>
<span id="cb76-334"><a href="#cb76-334" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-335"><a href="#cb76-335" aria-hidden="true" tabindex="-1"></a><span class="in">```{r value-values}</span></span>
<span id="cb76-336"><a href="#cb76-336" aria-hidden="true" tabindex="-1"></a><span class="co">#| eval: false</span></span>
<span id="cb76-337"><a href="#cb76-337" aria-hidden="true" tabindex="-1"></a><span class="co">#--- terra::values ---#</span></span>
<span id="cb76-338"><a href="#cb76-338" aria-hidden="true" tabindex="-1"></a>values_from_ml_sr <span class="ot">&lt;-</span> terra<span class="sc">::</span><span class="fu">values</span>(IA_cdl_ml_sr)</span>
<span id="cb76-339"><a href="#cb76-339" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-340"><a href="#cb76-340" aria-hidden="true" tabindex="-1"></a><span class="co">#--- take a look ---#</span></span>
<span id="cb76-341"><a href="#cb76-341" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(values_from_ml_sr)</span>
<span id="cb76-342"><a href="#cb76-342" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb76-343"><a href="#cb76-343" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-344"><a href="#cb76-344" aria-hidden="true" tabindex="-1"></a><span class="in">```{r values-show}</span></span>
<span id="cb76-345"><a href="#cb76-345" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: false</span></span>
<span id="cb76-346"><a href="#cb76-346" aria-hidden="true" tabindex="-1"></a><span class="co"># saveRDS(head(values_from_ml_sr), "Data/values-from-rs.rds")</span></span>
<span id="cb76-347"><a href="#cb76-347" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-348"><a href="#cb76-348" aria-hidden="true" tabindex="-1"></a>(</span>
<span id="cb76-349"><a href="#cb76-349" aria-hidden="true" tabindex="-1"></a>  values_from_rs <span class="ot">&lt;-</span> <span class="fu">readRDS</span>(<span class="st">"Data/values-from-rs.rds"</span>)</span>
<span id="cb76-350"><a href="#cb76-350" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb76-351"><a href="#cb76-351" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb76-352"><a href="#cb76-352" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-353"><a href="#cb76-353" aria-hidden="true" tabindex="-1"></a>**`[]`**</span>
<span id="cb76-354"><a href="#cb76-354" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-355"><a href="#cb76-355" aria-hidden="true" tabindex="-1"></a><span class="in">```{r value-square-bracket}</span></span>
<span id="cb76-356"><a href="#cb76-356" aria-hidden="true" tabindex="-1"></a><span class="co">#| eval: false</span></span>
<span id="cb76-357"><a href="#cb76-357" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-358"><a href="#cb76-358" aria-hidden="true" tabindex="-1"></a><span class="co">#--- terra::values ---#</span></span>
<span id="cb76-359"><a href="#cb76-359" aria-hidden="true" tabindex="-1"></a>values_from_ml_sr <span class="ot">&lt;-</span> IA_cdl_ml_sr[]</span>
<span id="cb76-360"><a href="#cb76-360" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-361"><a href="#cb76-361" aria-hidden="true" tabindex="-1"></a><span class="co">#--- take a look ---#</span></span>
<span id="cb76-362"><a href="#cb76-362" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(values_from_ml_sr)</span>
<span id="cb76-363"><a href="#cb76-363" aria-hidden="true" tabindex="-1"></a><span class="in">```</span> </span>
<span id="cb76-364"><a href="#cb76-364" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-365"><a href="#cb76-365" aria-hidden="true" tabindex="-1"></a><span class="in">```{r values-show-2}</span></span>
<span id="cb76-366"><a href="#cb76-366" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: false</span></span>
<span id="cb76-367"><a href="#cb76-367" aria-hidden="true" tabindex="-1"></a><span class="co"># saveRDS(head(values_from_ml_sr), "Data/values-from-rs.rds")</span></span>
<span id="cb76-368"><a href="#cb76-368" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-369"><a href="#cb76-369" aria-hidden="true" tabindex="-1"></a>(</span>
<span id="cb76-370"><a href="#cb76-370" aria-hidden="true" tabindex="-1"></a>  values_from_rs <span class="ot">&lt;-</span> <span class="fu">readRDS</span>(<span class="st">"Data/values-from-rs.rds"</span>)</span>
<span id="cb76-371"><a href="#cb76-371" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb76-372"><a href="#cb76-372" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb76-373"><a href="#cb76-373" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-374"><a href="#cb76-374" aria-hidden="true" tabindex="-1"></a>The returned values come in a matrix form of two columns because we are getting values from a two-layer <span class="in">`SpatRaster`</span> object (one column for each layer). In general, <span class="in">`terra::values()`</span> returns a $X$ by $n$ matrix, where $X$ is the number of cells and $n$ is the number of layers. </span>
<span id="cb76-375"><a href="#cb76-375" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-376"><a href="#cb76-376" aria-hidden="true" tabindex="-1"></a><span class="fu">### Subset (access particular layers)</span></span>
<span id="cb76-377"><a href="#cb76-377" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-378"><a href="#cb76-378" aria-hidden="true" tabindex="-1"></a>You can access specific layers in a multi-layer raster object by using the <span class="in">`subset()`</span> function with either the name of the layers or their numerical indices specified.</span>
<span id="cb76-379"><a href="#cb76-379" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-382"><a href="#cb76-382" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb76-383"><a href="#cb76-383" aria-hidden="true" tabindex="-1"></a><span class="fu">subset</span>(IA_cdl_ml_sr, <span class="st">"IA_cdl_2016"</span>)</span>
<span id="cb76-384"><a href="#cb76-384" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb76-385"><a href="#cb76-385" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-386"><a href="#cb76-386" aria-hidden="true" tabindex="-1"></a><span class="in">```{r }</span></span>
<span id="cb76-387"><a href="#cb76-387" aria-hidden="true" tabindex="-1"></a><span class="co">#--- second layer ---#</span></span>
<span id="cb76-388"><a href="#cb76-388" aria-hidden="true" tabindex="-1"></a><span class="fu">subset</span>(IA_cdl_ml_sr, <span class="dv">2</span>)</span>
<span id="cb76-389"><a href="#cb76-389" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb76-390"><a href="#cb76-390" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-391"><a href="#cb76-391" aria-hidden="true" tabindex="-1"></a>If you are accessing a single layer, you can use a familiar-looking syntax using <span class="in">`$`</span> like below:</span>
<span id="cb76-392"><a href="#cb76-392" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-395"><a href="#cb76-395" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb76-396"><a href="#cb76-396" aria-hidden="true" tabindex="-1"></a>IA_cdl_ml_sr<span class="sc">$</span>IA_cdl_2016</span>
<span id="cb76-397"><a href="#cb76-397" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb76-398"><a href="#cb76-398" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-399"><a href="#cb76-399" aria-hidden="true" tabindex="-1"></a><span class="fu">### Add a new layer</span></span>
<span id="cb76-400"><a href="#cb76-400" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-401"><a href="#cb76-401" aria-hidden="true" tabindex="-1"></a>You can create a new layer to a <span class="in">`SpatRaster`</span> object in a very similar syntax as creating a new variable to a <span class="in">`data.frame`</span> like below: </span>
<span id="cb76-402"><a href="#cb76-402" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-405"><a href="#cb76-405" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb76-406"><a href="#cb76-406" aria-hidden="true" tabindex="-1"></a><span class="co">#--- create a new layer called new_layer ---#</span></span>
<span id="cb76-407"><a href="#cb76-407" aria-hidden="true" tabindex="-1"></a>(</span>
<span id="cb76-408"><a href="#cb76-408" aria-hidden="true" tabindex="-1"></a>IA_cdl_ml_sr<span class="sc">$</span>new_layer <span class="ot">&lt;-</span> IA_cdl_ml_sr<span class="sc">$</span>IA_cdl_2016</span>
<span id="cb76-409"><a href="#cb76-409" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb76-410"><a href="#cb76-410" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb76-411"><a href="#cb76-411" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-412"><a href="#cb76-412" aria-hidden="true" tabindex="-1"></a>Here, we created a new layer called <span class="in">`new_layer`</span> to <span class="in">`IA_cdl_ml_sr`</span>, where the values stored in the new layer are simply the valuesn stored in the <span class="in">`IA_cdl_2016`</span> layer.</span>
<span id="cb76-413"><a href="#cb76-413" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-414"><a href="#cb76-414" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-415"><a href="#cb76-415" aria-hidden="true" tabindex="-1"></a><span class="fu">## Arithmetic operations</span></span>
<span id="cb76-416"><a href="#cb76-416" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-417"><a href="#cb76-417" aria-hidden="true" tabindex="-1"></a>You can do basic arithmetic operations (addition, subtraction, division, etc) using raster layers as long as they share the same spatial extent and resolution. </span>
<span id="cb76-418"><a href="#cb76-418" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-419"><a href="#cb76-419" aria-hidden="true" tabindex="-1"></a>Raster arithmetic operations are done **element-by-element** (cell-by-cell) just like vector arithmetic operations. That is, when two layers are added, then the two values associated with the same cell are added and the resulting value becomes the new value for the cell in the newly created RasterLayer.</span>
<span id="cb76-420"><a href="#cb76-420" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-421"><a href="#cb76-421" aria-hidden="true" tabindex="-1"></a>As a demonstration, let's try to calculate NDVI from NIR and RED. The mathematical definition of NDVI is as follows:</span>
<span id="cb76-422"><a href="#cb76-422" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-423"><a href="#cb76-423" aria-hidden="true" tabindex="-1"></a><span class="in">```{=tex}</span></span>
<span id="cb76-424"><a href="#cb76-424" aria-hidden="true" tabindex="-1"></a><span class="in">\begin{align}</span></span>
<span id="cb76-425"><a href="#cb76-425" aria-hidden="true" tabindex="-1"></a><span class="in">NDVI = (NIR-RED)/(NIR+RED)</span></span>
<span id="cb76-426"><a href="#cb76-426" aria-hidden="true" tabindex="-1"></a><span class="in">\end{align}</span></span>
<span id="cb76-427"><a href="#cb76-427" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb76-428"><a href="#cb76-428" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-429"><a href="#cb76-429" aria-hidden="true" tabindex="-1"></a>Let's first import NIR and RED.</span>
<span id="cb76-430"><a href="#cb76-430" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-433"><a href="#cb76-433" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb76-434"><a href="#cb76-434" aria-hidden="true" tabindex="-1"></a><span class="co">#| cache: false</span></span>
<span id="cb76-435"><a href="#cb76-435" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: read-nir-red</span></span>
<span id="cb76-436"><a href="#cb76-436" aria-hidden="true" tabindex="-1"></a>NIR_and_RED <span class="ot">&lt;-</span> terra<span class="sc">::</span><span class="fu">rast</span>(<span class="fu">c</span>(<span class="st">"Data/NIR.tif"</span>, <span class="st">"Data/RED.tif"</span>))</span>
<span id="cb76-437"><a href="#cb76-437" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb76-438"><a href="#cb76-438" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-439"><a href="#cb76-439" aria-hidden="true" tabindex="-1"></a>Let's use the formula to calculate NDVI:</span>
<span id="cb76-440"><a href="#cb76-440" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-443"><a href="#cb76-443" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb76-444"><a href="#cb76-444" aria-hidden="true" tabindex="-1"></a><span class="co">#| cache: false</span></span>
<span id="cb76-445"><a href="#cb76-445" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: calc-ndvi</span></span>
<span id="cb76-446"><a href="#cb76-446" aria-hidden="true" tabindex="-1"></a>NIR_and_RED<span class="sc">$</span>NDVI <span class="ot">&lt;-</span> (NIR_and_RED<span class="sc">$</span>NIR <span class="sc">-</span> NIR_and_RED<span class="sc">$</span>RED)<span class="sc">/</span>(NIR_and_RED<span class="sc">$</span>NIR <span class="sc">+</span> NIR_and_RED<span class="sc">$</span>RED)</span>
<span id="cb76-447"><a href="#cb76-447" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb76-448"><a href="#cb76-448" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-449"><a href="#cb76-449" aria-hidden="true" tabindex="-1"></a>Now, we have a layer named <span class="in">`NDVI`</span> in <span class="in">`NIR_and_RED`</span>.</span>
<span id="cb76-450"><a href="#cb76-450" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-451"><a href="#cb76-451" aria-hidden="true" tabindex="-1"></a>:::{.callout-note}</span>
<span id="cb76-452"><a href="#cb76-452" aria-hidden="true" tabindex="-1"></a>The <span class="in">`tidyterra`</span> package can help you make the codes a bit easier to read by allowing the user to use <span class="in">`dplyr`</span> verbs. For example, the above code can be written as below in place:</span>
<span id="cb76-453"><a href="#cb76-453" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-456"><a href="#cb76-456" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb76-457"><a href="#cb76-457" aria-hidden="true" tabindex="-1"></a>dplyr<span class="sc">::</span><span class="fu">mutate</span>(NIR_and_RED, <span class="at">NDVI =</span> (NIR <span class="sc">-</span> RED)<span class="sc">/</span>(NIR <span class="sc">+</span> RED))</span>
<span id="cb76-458"><a href="#cb76-458" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb76-459"><a href="#cb76-459" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-460"><a href="#cb76-460" aria-hidden="true" tabindex="-1"></a>There are other <span class="in">`dplyr`</span> verbs (not all) you can use to <span class="in">`SpatRaster`</span>. See <span class="co">[</span><span class="ot">here</span><span class="co">]()</span> for more detailed explanations of how <span class="in">`tidyterra`</span> works. We will use the package also to visualize <span class="in">`SpatRaster`</span> objected later in @sec-create-maps.</span>
<span id="cb76-461"><a href="#cb76-461" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb76-462"><a href="#cb76-462" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-463"><a href="#cb76-463" aria-hidden="true" tabindex="-1"></a>You can also apply mathematical functions to the layers like below^<span class="co">[</span><span class="ot">The calculated numers are not meaningful. This is just a demonstration of using mathematical functions.</span><span class="co">]</span>:</span>
<span id="cb76-464"><a href="#cb76-464" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-467"><a href="#cb76-467" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb76-468"><a href="#cb76-468" aria-hidden="true" tabindex="-1"></a><span class="fu">log</span>(NIR_and_RED<span class="sc">$</span>NIR) <span class="sc">+</span> NIR_and_RED<span class="sc">$</span>RED<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb76-469"><a href="#cb76-469" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb76-470"><a href="#cb76-470" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-471"><a href="#cb76-471" aria-hidden="true" tabindex="-1"></a><span class="fu">## Turning a raster object into a `data.frame` (not necessary)</span></span>
<span id="cb76-472"><a href="#cb76-472" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-473"><a href="#cb76-473" aria-hidden="true" tabindex="-1"></a>You can use the <span class="in">`as.data.frame()`</span> function with <span class="in">`xy = TRUE`</span> option to construct a <span class="in">`data.frame`</span> where each row represents a single cell that has cell values for each layer and its coordinates (the center of the cell).</span>
<span id="cb76-474"><a href="#cb76-474" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-475"><a href="#cb76-475" aria-hidden="true" tabindex="-1"></a><span class="in">```{r to-dataframe, eval = F}</span></span>
<span id="cb76-476"><a href="#cb76-476" aria-hidden="true" tabindex="-1"></a><span class="co">#--- converting to a data.frame ---#</span></span>
<span id="cb76-477"><a href="#cb76-477" aria-hidden="true" tabindex="-1"></a>IA_cdl_df <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(IA_cdl_stack_sr, <span class="at">xy =</span> <span class="cn">TRUE</span>) <span class="co"># this works with Raster* objects as well</span></span>
<span id="cb76-478"><a href="#cb76-478" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-479"><a href="#cb76-479" aria-hidden="true" tabindex="-1"></a><span class="co">#--- take a look ---#</span></span>
<span id="cb76-480"><a href="#cb76-480" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(IA_cdl_df)</span>
<span id="cb76-481"><a href="#cb76-481" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb76-482"><a href="#cb76-482" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-483"><a href="#cb76-483" aria-hidden="true" tabindex="-1"></a><span class="in">```{r to-dataframe-show, echo = F}</span></span>
<span id="cb76-484"><a href="#cb76-484" aria-hidden="true" tabindex="-1"></a><span class="co"># saveRDS(head(IA_cdl_df), "Data/IA_CDL_df.rds")</span></span>
<span id="cb76-485"><a href="#cb76-485" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-486"><a href="#cb76-486" aria-hidden="true" tabindex="-1"></a><span class="fu">readRDS</span>(<span class="st">"Data/IA_CDL_df.rds"</span>)</span>
<span id="cb76-487"><a href="#cb76-487" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb76-488"><a href="#cb76-488" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-489"><a href="#cb76-489" aria-hidden="true" tabindex="-1"></a>:::{.callout-important title="Caveat"}</span>
<span id="cb76-490"><a href="#cb76-490" aria-hidden="true" tabindex="-1"></a>I have seen cases where <span class="in">`raster`</span> objects are converted to a <span class="in">`data.frame`</span> and then to an <span class="in">`sf`</span> object for interacting with polygons using <span class="in">`sf::st_join()`</span> to extract and assign cell values to polygons (see @sec-int-vv for this type of operation). However, this approach is generally not recommended for two main reasons.</span>
<span id="cb76-491"><a href="#cb76-491" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-492"><a href="#cb76-492" aria-hidden="true" tabindex="-1"></a>First, it is significantly slower than using functions designed to work directly with raster objects and polygons, such as <span class="in">`terra::extract()`</span> or <span class="in">`exactextractr::exact_extract()`</span>, which are introduced in @sec-int-RV. The primary reason is that converting a raster to a data.frame is a time-consuming process.</span>
<span id="cb76-493"><a href="#cb76-493" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-494"><a href="#cb76-494" aria-hidden="true" tabindex="-1"></a>Second, once a raster object is converted to point <span class="in">`sf`</span> data, it becomes impossible to weight cell values based on their degree of overlap with the target polygons. While working with a <span class="in">`data.frame`</span> may be appealing due to their familiarity, the conversion is often unnecessary and inefficient^<span class="co">[</span><span class="ot">If you know of cases where converting to a `data.frame` is beneficial or necessary, please let me know, and I will include them here.</span><span class="co">]</span>.</span>
<span id="cb76-495"><a href="#cb76-495" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb76-496"><a href="#cb76-496" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-497"><a href="#cb76-497" aria-hidden="true" tabindex="-1"></a><span class="fu">## Quick visualization</span></span>
<span id="cb76-498"><a href="#cb76-498" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-499"><a href="#cb76-499" aria-hidden="true" tabindex="-1"></a>To have a quick visualization of the data values of <span class="in">`SpatRaster`</span> objects, you can simply use <span class="in">`plot()`</span>:</span>
<span id="cb76-500"><a href="#cb76-500" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-501"><a href="#cb76-501" aria-hidden="true" tabindex="-1"></a><span class="in">```{r plot_stack, cache = TRUE}</span></span>
<span id="cb76-502"><a href="#cb76-502" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(IA_cdl_2015_sr)</span>
<span id="cb76-503"><a href="#cb76-503" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb76-504"><a href="#cb76-504" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-505"><a href="#cb76-505" aria-hidden="true" tabindex="-1"></a>For a more elaborate map using raster data, see @sec-geom-raster. </span>
<span id="cb76-506"><a href="#cb76-506" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-507"><a href="#cb76-507" aria-hidden="true" tabindex="-1"></a><span class="fu">## Working with netCDFs {#sec-work-with-netcdf}</span></span>
<span id="cb76-508"><a href="#cb76-508" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-509"><a href="#cb76-509" aria-hidden="true" tabindex="-1"></a>A netCDF file contains data with a specific structure: a two-dimensional spatial grid (e.g., longitude and latitude) and a third dimension which is usually date or time. This structure is convenient for weather data measured on a consistent grid over time. One such dataset is called <span class="co">[</span><span class="ot">gridMET</span><span class="co">](http://www.climatologylab.org/gridmet.html)</span> which maintains a gridded dataset of weather variables at 4km resolution. Let's download the daily precipitation data for 2018 using <span class="in">`downloader::download()`</span>^<span class="co">[</span><span class="ot">gridMET data is also available in the [Google Earth Engine Data Catalog](https://developers.google.com/earth-engine/datasets/), which can be accessed with the R library [`rgee`](https://github.com/r-spatial/rgee)</span><span class="co">]</span>. We set the destination file name (what to call the file and where we want it to be), and the mode to <span class="in">`wb`</span> for a binary download. </span>
<span id="cb76-510"><a href="#cb76-510" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-513"><a href="#cb76-513" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb76-514"><a href="#cb76-514" aria-hidden="true" tabindex="-1"></a><span class="co">#| eval: false</span></span>
<span id="cb76-515"><a href="#cb76-515" aria-hidden="true" tabindex="-1"></a><span class="co">#--- download gridMET precipitation 2018 ---#</span></span>
<span id="cb76-516"><a href="#cb76-516" aria-hidden="true" tabindex="-1"></a>downloader<span class="sc">::</span><span class="fu">download</span>(</span>
<span id="cb76-517"><a href="#cb76-517" aria-hidden="true" tabindex="-1"></a>  <span class="at">url =</span> <span class="fu">str_c</span>(<span class="st">"http://www.northwestknowledge.net/metdata/data/pr_2018.nc"</span>),</span>
<span id="cb76-518"><a href="#cb76-518" aria-hidden="true" tabindex="-1"></a>  <span class="at">destfile =</span> <span class="st">"Data/pr_2018.nc"</span>,</span>
<span id="cb76-519"><a href="#cb76-519" aria-hidden="true" tabindex="-1"></a>  <span class="at">mode =</span> <span class="st">"wb"</span></span>
<span id="cb76-520"><a href="#cb76-520" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb76-521"><a href="#cb76-521" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb76-522"><a href="#cb76-522" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-523"><a href="#cb76-523" aria-hidden="true" tabindex="-1"></a>This code should have stored the data as **pr_2018.nc** in the **Data** folder. You can read a netCDF file using <span class="in">`terra::rast()`</span>.</span>
<span id="cb76-524"><a href="#cb76-524" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-525"><a href="#cb76-525" aria-hidden="true" tabindex="-1"></a><span class="in">```{r }</span></span>
<span id="cb76-526"><a href="#cb76-526" aria-hidden="true" tabindex="-1"></a>(</span>
<span id="cb76-527"><a href="#cb76-527" aria-hidden="true" tabindex="-1"></a>  pr_2018_gm <span class="ot">&lt;-</span> terra<span class="sc">::</span><span class="fu">rast</span>(<span class="st">"Data/pr_2018.nc"</span>)</span>
<span id="cb76-528"><a href="#cb76-528" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb76-529"><a href="#cb76-529" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb76-530"><a href="#cb76-530" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-531"><a href="#cb76-531" aria-hidden="true" tabindex="-1"></a>You can see that it has 365 layers: one layer per day in 2018. Let's now look at layer names:  </span>
<span id="cb76-532"><a href="#cb76-532" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-533"><a href="#cb76-533" aria-hidden="true" tabindex="-1"></a><span class="in">```{r }</span></span>
<span id="cb76-534"><a href="#cb76-534" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(<span class="fu">names</span>(pr_2018_gm))</span>
<span id="cb76-535"><a href="#cb76-535" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb76-536"><a href="#cb76-536" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-537"><a href="#cb76-537" aria-hidden="true" tabindex="-1"></a>Since we have 365 layers and the number at the end of the layer names increase by 1, you would think that **n**th layer represents **n**th day of 2018. In this case, you are correct. However, it is always a good practice to confirm what each layer represents without assuming anything. Now, let's use the <span class="in">`ncdf4`</span> package, which is built specifically to handle netCDF4 objects.</span>
<span id="cb76-538"><a href="#cb76-538" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-539"><a href="#cb76-539" aria-hidden="true" tabindex="-1"></a><span class="in">```{r }</span></span>
<span id="cb76-540"><a href="#cb76-540" aria-hidden="true" tabindex="-1"></a>(</span>
<span id="cb76-541"><a href="#cb76-541" aria-hidden="true" tabindex="-1"></a>  pr_2018_nc <span class="ot">&lt;-</span> ncdf4<span class="sc">::</span><span class="fu">nc_open</span>(<span class="st">"Data/pr_2018.nc"</span>)</span>
<span id="cb76-542"><a href="#cb76-542" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb76-543"><a href="#cb76-543" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb76-544"><a href="#cb76-544" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-545"><a href="#cb76-545" aria-hidden="true" tabindex="-1"></a>As you can see from the output, there is tons of information that we did not see when we read the data using <span class="in">`rast()`</span>, which includes the explanation of the third dimension (day) of this raster object. It turned out that the numerical values at the end of layer names in the <span class="in">`SpatRaster`</span> object are **days since 1900-01-01**. So, the first layer (named **precipitation_amount_day=43099**) represents:</span>
<span id="cb76-546"><a href="#cb76-546" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-547"><a href="#cb76-547" aria-hidden="true" tabindex="-1"></a><span class="in">```{r }</span></span>
<span id="cb76-548"><a href="#cb76-548" aria-hidden="true" tabindex="-1"></a>lubridate<span class="sc">::</span><span class="fu">ymd</span>(<span class="st">"1900-01-01"</span>) <span class="sc">+</span> <span class="dv">43099</span></span>
<span id="cb76-549"><a href="#cb76-549" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb76-550"><a href="#cb76-550" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-551"><a href="#cb76-551" aria-hidden="true" tabindex="-1"></a>Actually, if we use <span class="in">`raster::brick()`</span>, instead of <span class="in">`terra::rast()`</span>, then we can see the naming convention of the layers:</span>
<span id="cb76-552"><a href="#cb76-552" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-553"><a href="#cb76-553" aria-hidden="true" tabindex="-1"></a><span class="in">```{r }</span></span>
<span id="cb76-554"><a href="#cb76-554" aria-hidden="true" tabindex="-1"></a>(</span>
<span id="cb76-555"><a href="#cb76-555" aria-hidden="true" tabindex="-1"></a>  pr_2018_b <span class="ot">&lt;-</span> raster<span class="sc">::</span><span class="fu">brick</span>(<span class="st">"Data/pr_2018.nc"</span>)</span>
<span id="cb76-556"><a href="#cb76-556" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb76-557"><a href="#cb76-557" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb76-558"><a href="#cb76-558" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-559"><a href="#cb76-559" aria-hidden="true" tabindex="-1"></a><span class="in">`SpatRaster`</span> or <span class="in">`RasterBrick`</span> objects are easier to work with as many useful functions accept them as inputs, but not the <span class="in">`ncdf4`</span> object. Personally, I first scrutinize a netCDFs file using <span class="in">`nc_open()`</span> and then import it as a <span class="in">`SpatRaster`</span> or <span class="in">`RasterBrick`</span> object^<span class="co">[</span><span class="ot">Even though `RasterBrick` provides the description of how layers are named, I think it is a good practice to see the full description in the `ncdf4` object.</span><span class="co">]</span>. Recovering the dates for the layers is particularly important as we often wrangle the resulting data based on date (e.g., subset the data so that you have only April to September). An example of date recovery can be seen in @sec-gridMET.</span>
<span id="cb76-560"><a href="#cb76-560" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-561"><a href="#cb76-561" aria-hidden="true" tabindex="-1"></a>For those who are interested in more detailed descriptions of how to work with <span class="in">`ncdf4`</span> object is provided <span class="co">[</span><span class="ot">here</span><span class="co">](https://pjbartlein.github.io/REarthSysSci/netCDF.html)</span>.</span>
<span id="cb76-562"><a href="#cb76-562" aria-hidden="true" tabindex="-1"></a></span>
</code><button title="Copy to Clipboard" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></pre></div>
</div></div></div></div></div>
</div> <!-- /content -->



<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/tmieno2/R-as-GIS-for-Economists/edit/master/chapters/03-RasterDataBasics.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li></ul></div></div></div></footer></body></html>